### ISSUE TITLE
IPSec IKEv2

### ISSUE THREAD

**Issue by chenhouwu** [jlund/streisand#110]
Would like to have support of IPSec without l2tp.
l2tp is blocked often by GFW,
I hear that IKEv2 is never blocked.

**Comment by peterpacz1** [comment]
Agreed - IPSec is indeed blocked in China, although I am unable to verify the part about Cisco IPsec. It's still worth looking into, however.

**Comment by mveplus** [comment]
L2TP/IPSec still works fine in some areas, but IKEv2 option as well will be great add on too!

**Comment by stevemcquaid** [comment]
IKEV2 will enable always-on features in android + iOS8

**Comment by stevemcquaid** [comment]
Am happy to dev this - just dont want to screw up the security of it

**Comment by stevemcquaid** [comment]
Would any core contribs be willing to help me get started?

**Comment by jlund** [comment]
I've been looking into this today. I think it probably makes the most sense to also use Libreswan for IKEv2 and to provide users with a choice during the setup process between L2TP/IPsec and IKEv2 (probably defaulting to L2TP/IPsec).

That approach would involve breaking Libreswan into a shared role that both the L2TP/IPsec and IKEv2 roles could depend upon. Each role would then just apply the correct configuration to the installation. I'm going to try to find some time over the next couple of weeks to get this done.

@stevemcquaid: If you wanted to come up with a working IKEv2 configuration for Libreswan, that would be really helpful. They have a couple of examples on their Wiki, but I haven't had a chance to try them yet. We can easily create a dedicated user on new Streisand servers and rely on the PAM integration that appears to be present in Libreswan.

On a related note, the iOS support for an always-on VPN is pretty terrible in my recent testing. You have to completely wipe and reset the phone or tablet in order to enable supervision, and then you have to create and apply a Configuration Profile. You cannot re-apply an existing backup after performing these steps; you truly need to start from scratch on your chosen device.

Furthermore, an iOS device that has an always-on VPN enabled truly means that it is _always_ on. If the VPN ever goes down for any reason, you completely lose access to the Internet. You cannot disable the always-on VPN from the phone itself, and you must update the Configuration Profile using Apple's Configurator tool on an OS X machine (or have access to a Mobile Device Management Server). Given all of that, always-on VPN support isn't really something that would work well for the average Apple user, which is a shame. The situation on Android is much better.

IKEv2 is a far more modern protocol with better roaming and multiple-client support. Even though it isn't as widely supported as L2TP/IPsec, it will be a good option to have.

**Comment by stevemcquaid** [comment]
Thank you so much @jlund for the thoughtful and detailed post

I am actually in the process right now of getting this working via manual config for a Proof-Of-Concept: https://expats-in-china.com/t/setup-a-vpn-ipsec-on-centos-7-using-strongswan/27. Based on your thoughts, I will switch to libreswan.

Your points about the tough configuration are spot-on.  Is there anything we can do except wait for native support to get better?

**Comment by jlund** [comment]
That guide looks like a really good start.

I'm hoping that iOS 10 exposes always-on VPN as an option that doesn't require a Configuration Profile. Right now it appears to be targeted exclusively to corporate users and company-owned devices. I think we would be leading people down a very sad road and potentially causing more harm than good (e.g. wiped phones and lost pictures) by trying to make always-on VPN instructions for iOS part of Streisand's documentation right now.

**Comment by moralrebuild** [comment]
half year has passed. any progress on this feature?

**Comment by jessechahal** [comment]
I think most people now who want this feature have switched over to: https://github.com/trailofbits/algo

**Comment by TychoSchenkeveld** [comment]
I didn't know about Algo, nice!!

I would use it, however.... I have *both* Android and iOS devices, and as Android does not support IKEv2, I need L2TP as well. Which Algo does not support :(

I know you can install the StrongARM client but Android can only use L2TP for "Always-On" VPN and I don't want to be constantly switching my VPN on (and risking data going out unencrypted when it drops off).

By the way I agree with some of their Streisand criticism, in particularly I don't like it installing a tor node without asking. It's frowned upon at some hosting providers, because of all the illegal stuff it's associated with. But I uninstalled tor immediately, it's easy to do.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/21
