### ISSUE TITLE
A request for Docker Image

### ISSUE THREAD

**Issue by aminbolehvpn** [jlund/streisand#126]
Hi Joshua,
Is it possible to have docker images? It will do the deployment of streisand a lot quicker to novices.

**Comment by jlund** [comment]
I can look into this again, but when I last checked there were lots of incompatibilties. For example, OpenVPN needs to make a TUN interface, and that didn't work inside of a container. It would also be tough to do the mirroring, unique keys, unique certificates, etc. in a prepackaged way.

**Comment by aminbolehvpn** [comment]
I've seen a number of openvpn docker images surfacing lately and have run a
few of them and seems to be working but only for small number of users
connecting to it. You can assign sharedfolders to the mirroring instead of
keeping them in the docker containers.

**Comment by jlund** [comment]
Yeah, it's definitely a worthwhile thing to reattempt.

**Comment by dlmetcalf** [comment]
If this comes up again, there's an Ansible-Containers project just released, which may be useful since rest of the project is in Ansible: http://docs.ansible.com/ansible-container/

I haven't kicked the tires on it and have no idea whether that'd expose all the necessary Docker functionality, or just a subset.

Considering security requirements of this project; if Docker is considered again, I'd recommend reviewing security implementation recommendations here too: https://www.nccgroup.trust/us/our-research/understanding-and-hardening-linux-containers/  (Pages 105-108 particularly).

**Comment by joaocc** [comment]
Try these:
* https://github.com/sw00/docker-streisand
* https://github.com/gdoteof/docker-streisand

**Comment by joaocc** [comment]
@jlund Any moves towards having a docker image (or a set of them via docker services) to have Streisand services running on a local machine (or any docker host)? Thanks

**Comment by jamesmstone** [comment]
would be keen to help with this, but no idea where to begin...

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/20
