### ISSUE TITLE
Documentation Needed for Streisand on Wiki

### ISSUE THREAD

**Issue by ShenZhouHong** [jlund/streisand#130]
Hello, this is a minor issue but I believe it must be addressed regardless.

For the past two weeks or so, at least 10% of the bug reports are due to users not understanding how to properly install streisand locally, or some other minor non-coding related issue that can be solved through more comprehensive documentation.

Although the main page on streisand provides excellent information, I think it's vital for us to provide some more in depth information (such as how to install streisand locally), on the Github wiki for streisand. I've gone ahead and created the barebones framework for 3 pages, but more help is needed in writing these docs.

**Comment by skeeve42** [comment]
So you can install streisand locally now--on a single machine without having to connect from another machine?

**Comment by cpu** [comment]
> So you can install streisand locally now--on a single machine without having to connect from another machine?

Yes. This is officially supported with the latest code from master.

I don't think there is a need for Wiki documentation for local installation mode so I'm going to close this issue. If confusion persists we can revisit but where possible I'd like to address common user error /traps in the Streisand wrapper & roles instead of requiring more documentation.

Thanks!
