### ISSUE TITLE
Please add support for localization

### ISSUE THREAD

**Issue by L-Cafe** [jlund/streisand#153]
I need two things:

First, the script running in terminal will ask the language, displaying it from the list of available languages.

Second, the web server will ask for the language upon logging in (and if possible, set a cookie).

I'm willing to fully translate the project to spanish, once this is done, by forking the project and editing the necessary files (either the whole HTML and bash scripts or otherwise, using a translation tool that lists all the strings necessary in a single file, such as poedit). When I'm done, I'll submit a pull request. I'm a native spanish speaker from Spain.

**Comment by jlund** [comment]
This sounds fantastic.

What if we used language prefixes on the server instead (e.g. /en/index.html, /es/index.html, etc.)?

**Comment by pyrobisqit** [comment]
Yeah, that should keep things tidy. I'm up for that! :smile:

**Comment by Edzilla2000** [comment]
I'd love to help on something like that. I'm setting up Streisand for friends and family, but for most of them technical instructions in English are really not an option.
I'd be able to help on french translation.

**Comment by mbravorus** [comment]
I'm aiming to pitch in with Russian translations. Will start with a simple README.md translation, hoping that the work on French l10n by alimakki will get incorporated, including the language selector, and then I'd gladly contribute translating instructions for the packages/services

**Comment by alimakki** [comment]
@mbravorus i18n is now merged

**Comment by cpu** [comment]
The framework for localization support is here. Translations & improvements welcome as PRs! I'm going to close this issue. Thanks everyone (especially @alimakki :tada:!!)

**Comment by shelhezan** [comment]
I'd like to chip in with a German translation but I'm having trouble to determine the files which have to be translated.
In quick and dirty way I'd shuffle through all the folders and translate everything that's not nailed or screwed down. Is this recommeded?

**Comment by alimakki** [comment]
Hi @shelhezan, I can help with that.

I'll check back and follow up with a list of all the files I've touched when I worked on the French localization.

My rule of thumb is that anything a user sees in the gateway has to be translated.

**Comment by alimakki** [comment]
Hello again @shelhezan,

I dug up the [i18n_fr](https://github.com/jlund/streisand/pull/677/files) PR, here are the files that have been translated/updated:

- README (created a README-fr)
- playbooks/roles/common/vars/main.yml (add a new language to streisand_languages dict)
- playbooks/roles/l2tp-ipsec/templates/instructions.md.j2 (created a instructions-fr.md.j2)
- playbooks/roles/openconnect/templates/instructions.md.j2 (ditto)
- playbooks/roles/openvpn/templates/instructions.md.j2 (ditto)
- playbooks/roles/openvpn/templates/stunnel-instructions.md.j2 (ditto)
- playbooks/roles/shadowsocks/templates/instructions.md.j2 (ditto)
- playbooks/roles/ssh/templates/instructions.md.j2 (ditto)
- playbooks/roles/streisand-gateway/templates/firewall.md.j2 (firewall-fr.md.j2)
- playbooks/roles/streisand-gateway/templates/index.md.j2 (index-fr.md.j2)
- playbooks/roles/streisand-gateway/templates/instructions.md.j2 (instructions-fr.md.j2)
- playbooks/roles/streisand-mirror/templates/mirror-index.md.j2 (mirror-index-fr.md.j2)
   (Note: due to modularization, a lot of mirrors have been refactored into roles, see #746)
- playbooks/roles/tor-bridge/templates/instructions.md.j2 (instructions-fr.md.j2)
- playbooks/roles/wireguard/templates/instructions.md.j2 (ditto)

**Comment by shelhezan** [comment]
Hi @alimakki,

thank you for the list and the clarification. I'll fork streisand and prep the PR. That shouldn't last longer than an evening to do. I'll get back to you guys for reviewing the final stuff.
