### ISSUE TITLE
Tor ended 32 bit support, can't install 

### ISSUE THREAD

**Issue by arronhunt** [jlund/streisand#155]
```
failed: [104.236.167.13] => (item=https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg"}
msg: Request failed
failed: [104.236.167.13] => (item=https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg.asc", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/4.5/TorBrowser-4.5-osx32_en-US.dmg.asc"}
msg: Request failed
```

Looks like Tor only supports 64 bit now https://blog.torproject.org/blog/tor-browser-45-released

Those distros no longer work and I can't configure streisand because it is erroring out. 

edit: Additionally, why does it need to download the .dmg if I'm installing this on Ubuntu?

**Comment by jlund** [comment]
This should be fixed now. Streisand mirrors the Tor Browser Bundle and other common client files across several platforms because the official download locations are typically blocked in repressive countries. You may not be using OS X, but if you choose to share the generated instructions file with someone who is, they'll be able to get set up no matter where they are. That's the hope anyway :)

Thanks for letting me know!
