### ISSUE TITLE
Direct all traffic through Tor

### ISSUE THREAD

**Issue by Ge0rges** [jlund/streisand#162]
I'm not a server wiz but I wanted to know if it is possible to route all traffic from the server through the Tor relay system for added encryption and privacy layers. Similar to AirVPMN over Tor or Tor over AirVPN.

**Comment by jlund** [comment]
You could route OpenVPN connections (or other connections) over Tor on your system using its built-in SOCKS proxy. Streisand sets up a Tor Bridge that could be used for this purpose as the first part of a Tor circuit. You can also connect to the Tor network directly using the Tor Browser Bundle. In general, you probably want to be using the Tor Browser Bundle in conjunction with Tor because it includes several protections against browser fingerprinting and it also blocks plugins (such as Flash) that might otherwise harm anonymity.
