### ISSUE TITLE
Install this on existing Digital Ocean server?

### ISSUE THREAD

**Issue by Ge0rges** [jlund/streisand#164]

**Comment by jlund** [comment]
This capability will be added soon.

**Comment by TheDoctorsLife** [comment]
I'd also like to see this feature

**Comment by protofab** [comment]
any updates? i'm trying to deploy to digital ocean.

**Comment by cpu** [comment]
This has been possible since https://github.com/jlund/streisand/pull/724 was merged into master:

1) Clone the Streisand repo to your local client machine (laptop, desktop, etc)
2) Follow the setup instructions to install Streisand's dependencies (python, pip, Ansible)
3) Run `./streisand`
4) Choose the existing server option and enter the IP address of the existing Digital Ocean droplet.
