### ISSUE TITLE
Redirect from http to https?

### ISSUE THREAD

**Issue by TabTwo** [jlund/streisand#186]
I think it would make using streisand easier to use if nginx was configured in this way.

**Comment by mveplus** [comment]
Redirect 80 to 443:
Edit /etc/nginx/sites-available/streisand and add this:
# Redirect port 80 to 443
server {
    listen       80;
    return 301 https://$host$request_uri;
 }
Restart Nginx, make sure your iptables allow tcp on post 80.

**Comment by cpu** [comment]
This feature request will be complicated by the tor-bridge role. Right now it [configures the torrc config to listen on 80](https://github.com/jlund/streisand/blob/b850517fa5d6966ca5d8719c2bc2094d5a83ea4b/playbooks/roles/tor-bridge/templates/torrc.j2#L13). I believe this would have to be moved to a different port for there to be an HTTP -> HTTPS redirect for the Gateway website.

**Comment by cpu** [comment]
I'm going to close this issue. I think implementing it as requested will be difficult given the tor-bridge role. Overall I don't think the current configuration with the gateway only accessible on 443 is a usability problem because we expressly generate the correct `https:` links in the generated documentation that is intended to be shared with end-users.

Thanks!
