### ISSUE TITLE
question regarding Google DNS resolvers

### ISSUE THREAD

**Issue by summerjob** [jlund/streisand#194]
Probably not an issue - more of a concern.
If I connect via 'OpenVPN direct' and run a DNS leak test I get a long list of google servers resolving my DNS queries. These google DNS servers are all located in the same country as my VPNs location so I guess this should be correct.
In my OpenVPN client I use the option 'set nameserver by VPN server' which changes my usual ISPs DNS to custom DNS 10.8.0.1 - again I guess this is the standard behaviour of Streisand.

My question is:
- Why is google involved at all in my queries? This is the main company I wanted to get away from in the first place. Isn't Google storing all of my requests under my VPN IP?
- Can I set other DNS servers than google in Streisand? I know it's possible if I change the network settings of my PC but I wonder where I can set this in Streisand.

**Comment by pyrobisqit** [comment]
This is because DNS queries are forced through the streisand server. This is done to:
- Encrypt DNS queries at client level (it uses the same encryption as the transport tunnel).
- Avoid DNS spoofing by your ISP.

To change the DNS resolvers, you need to change the settings in the streisand server. The streisand server will then push the DNS settings through the tunnel, and the streisand server will keep encrypting DNS traffic, acting as a proxy.

**Comment by summerjob** [comment]
Thank you for your reply @pyrobisqit !
- Just to clarify: my google queries are "encrypted" - I understand that means my ISP can't see my queries but Google still knows everything I enter. Is this correct?
- I looked through the package files but couldn't find where to change "google dns servers" to my preferred no-logging DNS servers. Do you know which file to modify?

**Comment by summerjob** [comment]
Thank you for your reply @pyrobisqit !
- Just to clarify: my google queries are "encrypted" - I understand that means my ISP can't see my queries but Google still knows everything I enter. Is this correct?
- I looked through the package files but couldn't find where to change "google dns servers" to my preferred no-logging DNS servers. Do you know which file to modify?
