### ISSUE TITLE
Where to set own DNS servers in Streisand?

### ISSUE THREAD

**Issue by summerjob** [jlund/streisand#195]
I looked through the package files but couldn't find where to change the preset "google dns servers" to my preferred no-logging DNS servers.

Could you let me know which file to modify?

**Comment by aeibrahim** [comment]
Looks like it's using dnsmasq forwarding upstream to Google's DNS servers. If you want to change it, you'll need to modify: `playbooks/roles/openvpn/files/etc_dnsmasq.conf`

set your DNS servers here:

    # Add other name servers here, with domain specs if they are for
    # non-public domains.
    server=8.8.8.8
    server=8.8.4.4

**Comment by jlund** [comment]
Thanks to @aeibrahim's pull request (#197) there is now a single file where you can change the default DNS servers for both OpenVPN and L2TP/IPsec: `playbooks/group_vars/all`.

What servers would you recommend instead, @summerjob? Google's DNS servers were the only ones I tested that were reliable, free, and that didn't do sketchy things like redirecting to "guide" sites filled with advertisements in the event of a typo (instead of just sending a normal NXDOMAIN for something that doesn't exist). Google's [DNS privacy policy](https://developers.google.com/speed/public-dns/privacy) also struck me as reasonable.

I'm definitely not opposed to changing the defaults, but I wouldn't want to do that unless all three of those boxes are still being checked.
