### ISSUE TITLE
fails to generate Tor obfs3 QR code

### ISSUE THREAD

**Issue by kydan** [jlund/streisand#205]
I've done a recent git pull to my repo and am generating a new server with the latest commits. Continuously fails on the following task:

```TASK: [tor-bridge | Generate the Tor obfs3 QR code] *************************** 
fatal: [my_ip_here] => Failed to template echo -n '{{ tor_obfs3_bridge_line | urlencode }}' | qrencode -s 12 -o {{ tor_obfs3_qr_code }}: template error while templating string: no filter named 'urlencode'```


as an aside, is there an easy way to pick up a failed setup from point of failure, or do you have to start from the top each time?

**Comment by jlund** [comment]
It looks like you are using a version of the Jinja2 templating language that does not have support for the `urlencode` filter (which was added in version 2.7). How did you install Ansible, and what platform are you on?

If you installed using pip, the following command should update Jinja2 to the latest version:
`pip install Jinja2 --upgrade`

Ubuntu is also shipping Jinja2 v2.8 in the 15.10 repository.

As for starting at a given task, you can run the `streisand.yml` playbook against a given server using Ansible directly with the `--start-at-task` flag. Ideally, nothing should be failing though :)

If this turns out to be a common problem, it should be relatively easy to do the URL encoding step in a different manner instead of using the somewhat new `urlencode` Jinja2 filter.

**Comment by jlund** [comment]
I just changed this task to use the native `urllib` Python library. This should solve the issue that you were having, even if you continue to use a pre-2.7 version of Jinja2.
