### ISSUE TITLE
Putty mirror appears to be down

### ISSUE THREAD

**Issue by kydan** [jlund/streisand#210]
I've hit the mirror from multiple hosts in both Asia and the US and getting either a connection refused or a perms error. Any particular reason you picked tartarus.org as the mirror in lieu of 
http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe which appears to the be the "official" mirror @jlund? 
````
TASK: [streisand-mirror | Mirror the PuTTY files and signatures] ************** 
failed: [128.199.107.64] => (item=http://tartarus.org/~simon/putty-snapshots/x86/putty.exe) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://tartarus.org/~simon/putty-snapshots/x86/putty.exe", "mode": "0755", "owner": "www-data", "response": "HTTP Error 403: Forbidden", "size": 4096, "state": "directory", "status_code": 403, "uid": 33, "url": "http://tartarus.org/~simon/putty-snapshots/x86/putty.exe"}
msg: Request failed
failed: [128.199.107.64] => (item=http://tartarus.org/~simon/putty-snapshots/x86/putty.exe.gpg) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://tartarus.org/~simon/putty-snapshots/x86/putty.exe.gpg", "mode": "0755", "owner": "www-data", "response": "HTTP Error 403: Forbidden", "size": 4096, "state": "directory", "status_code": 403, "uid": 33, "url": "http://tartarus.org/~simon/putty-snapshots/x86/putty.exe.gpg"}
msg: Request failed

FATAL: all hosts have already failed -- aborting
````

**Comment by jlund** [comment]
Back in September, [PuTTY changed their release keys](https://github.com/jlund/streisand/issues/191). However, they were still publishing a release version that hadn't yet been signed by the new release key. Rather than awkwardly refactoring the tasks in the [download and verify step](https://github.com/jlund/streisand/blob/master/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml) so they would take into account this strange state of affairs, I temporarily switched to mirroring the development snapshot instead.

The tartarus.org URL that you mentioned is the official mirror location for PuTTY development snapshots, which is in line with the PuTTY project's somewhat charming tradition of using as many domains with as many old-school tilde-style home directories on as many SSL-disabled servers as possible.

Anyway, their release keys actually sign the latest release version again! So Streisand is back to mirroring that.

**Comment by jlund** [comment]
I forgot to say this: Thanks for letting me know!

**Comment by kydan** [comment]
Of course!

sent from my mobile
2015年11月29日 上午5:15，"Joshua Lund" <notifications@github.com>写道：
