### ISSUE TITLE
Doesn't work out of the box. OSX + Digital Ocean.

### ISSUE THREAD

**Issue by stevekuato** [jlund/streisand#233]
Ubuntu 14.04.

After installing (error free) I am unable to open the SSL connection instructions as they just send me to my server's IP address (HTTPS) which Chrome says is insecure and not trusted. If I force Chrome to connect, it just displays the default website on my server.
Note my server has a website running on port 443 with a valid SSL cert I previously purchased. This is the website I see when trying to view the SSL connection instructions.

I can get the TOR connection instructions to open OK.

I then followed the steps to install TunnelBlick etc. (OpenVPN stunnel) but it is unable to connect.

2016-02-01 04:58:38 MANAGEMENT: >STATE:1454273918,TCP_CONNECT,,,
2016-02-01 04:58:39 TCP: connect to [AF_INET]127.0.0.1:41194 failed, will try again in 5 seconds: Connection reset by peer

I then tried following the Shadowsocks instructions, but this also does not connect. The error in the Shadowsocks log is:

01/02/2016 05:04:44.937 lsd[285]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist

So I then tried to do a L2TP connection and when connecting I get the following error:

The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

My server is not offline.

Do you have any idea how I can investigate what's wrong?

Thanks.

**Comment by stevekuato** [comment]
I just tried the TOR method as well (custom bridges option) and that also does not work. It gets stuck on "Establishing a Tor circuit".

Note I can normally use TOR without using this custom bridge, so TOR is not blocked where I am.

01/02/2016, 05:28:43.500 [WARN] Proxy Client: unable to connect to xxxxxxxx:52488 ("general SOCKS server failure") 

xxxxxxxx is my IP address.

**Comment by jlund** [comment]
Did you run this against an existing server? Because, yeah, that would potentially cause a lot of problems and almost nothing would work. :(

**Comment by stevekuato** [comment]
Thanks for your reply.

I created a server today, put a website on it (nginx), installed a valid SSL cert and configured nginx to redirect port 80 to port 443.

The server is on Digital Ocean, although it is via a partner called BitHost.io. It's a plain Ubuntu 14.04.

Rather than choosing the Digital Ocean option during the install (not really possible because I use BitHost.io) I edited playbooks/streisand.yml  & ansible.cfg to use my correct IP and server name. I also commented out host_key_checking = False in ansible.cfg.

I then installed using ansible-playbook playbooks/streisand.yml

The installer didn't produce any errors.

What do you recommend I do to get this to work? Ideally I'd like to use this server... 

Thank you.

**Comment by jlund** [comment]
Streisand also installs and configures Nginx; generates a custom SSL certificate; and puts sslh in front so that HTTPS, OpenVPN, and SSH can all share port 443 in order to get around some restrictive WiFi networks. There are likely several other conflicts that are happening as well. Streisand is designed to be run against a brand-new server that hasn't already been customized. 

I'm _really_ relieved to hear that this wasn't a long-running server that was actively handling other websites or services. I'm going to add protection for this scenario so that users are warned if they attempt to run the playbook on a server that isn't new. 

Although I've never used that particular host before, Streisand works well on any new Ubuntu 14.04 server. DigitalOcean is probably the most popular VPS provider for Streisand users, and I configured several working servers there yesterday while I was testing some recent updates.

If you want to use a custom SSL certificate, it's probably best to set that up after the installation finishes on a fresh server. I haven't ever done this before though. By default, the connection instructions explain how to install the custom and unique SSL certificate in your browser so that you can hit the Streisand gateway IP over SSL without any warnings. This approach is arguably more secure than a traditional SSL certificate because Certificate Authorities don't issue certificates for bare IPs.

**Comment by stevekuato** [comment]
Thanks for your message.

I got it to work. :)

I set it up on a new server, and then moved my website onto this new server after I had tested everything was working. I had to tweak the nginx settings a bit to get my website to work, but it wasn't too difficult.

Thanks for the great product!

**Comment by jlund** [comment]
Nice! I'm glad that it's working. You're welcome!
