### ISSUE TITLE
Feature request: User management / Access revocation

### ISSUE THREAD

**Issue by stevekuato** [jlund/streisand#235]
I guess this is a question more than a feature request.

How would I go about revoking access to someone who I previously sent the HTML instructions to?

Is there a process for this? (e.g. regenerate the passwords + HTML file.)

Thanks.

**Comment by MinimaxHeadroom** [comment]
:+1: Excellent question. I also wish to know if there's some recommended process for revoking a certificate and otherwise disallowing connections to anyone with prior VPN access.

Otherwise, a certificate management feature such as this—not unlike the one [present](https://github.com/Nyr/openvpn-install/blob/aa5c024b8ec7909118743fcda7a813f603ca6e61/openvpn-install.sh#L73) in the OpenVPN road warrior script—would be incredibly helpful.

For reference, I found [this](http://serverfault.com/a/472961) Server Fault answer regarding OpenVPN certificate revocation, which itself references [related OpenVPN documentation](http://openvpn.net/index.php/open-source/documentation/howto.html#revoke).

Unfortunately, I'm not familiar enough with OpenVPN's cert revocation process, nor with the software's implementation in Streisand, to contribute the necessary code. I'm more than willing to help test out such a feature, however.

**Comment by jlund** [comment]
I would probably recommend just setting up a new server and shutting the old one down. If you have to reconfigure your clients anyway, it doesn't seem like revocation would save very much time at all--especially if you have to do it across every single service.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/16
