### ISSUE TITLE
tor not actually starting on ubuntu 14.04

### ISSUE THREAD

**Issue by kennyluk** [jlund/streisand#239]
Noticed that the tor daemon is not starting

![screen shot 2016-02-02 at 15 36 42](https://cloud.githubusercontent.com/assets/8308109/12742919/da87a870-c9c4-11e5-9c8c-c5d0b0fe8cac.png)

Found the solution here: http://askubuntu.com/questions/491190/tor-not-working-after-update

**Comment by andreagrax** [comment]
me too on virtualbox , quick fix
`sudo sed -i 's/AA_EXEC_ARGS="--profile=system_tor -- $DAEMON"/AA_EXEC_ARGS="-f system_tor -- $DAEMON"/' /etc/init.d/tor `

**Comment by cpu** [comment]
This issue is too stale to be actionable. Ubuntu 14.04 is no longer a supported Streisand server OS. All Streisand instances are created on top of Ubuntu 16.04 at present. If you find this issue still persists using the latest code from master on a fresh 16.04 instance please create a new issue providing the information requested by the issue template. Thanks!
