### ISSUE TITLE
Fail2ban: potential conflicts?

### ISSUE THREAD

**Issue by MinimaxHeadroom** [jlund/streisand#243]
I'm curious to know what issues might arise with installing the [Fail2ban](https://.com/fail2ban/fail2ban) daemon on the Streisand server to monitor and block unauthorized login attempts.

UFW and Fail2ban should play together fine, however, are there other pre-configured server settings which may potentially conflict with this tool's installation?

**Comment by jlund** [comment]
Just out of curiosity, which services would you want it to monitor and block?

Streisand does its best to make sure that client activity isn't logged at all for any running VPN service. This includes doing things like [modifying the OpenSSH log level](https://github.com/jlund/streisand/blob/master/playbooks/roles/ssh/tasks/main.yml#L8) to disable information about incoming SSH connections. Fail2ban uses logs like these in order to trigger the firewall rules that it creates.

However, Streisand also does its best to keep new servers secure by [disabling password-based SSH logins in favor of public-key auth](https://github.com/jlund/streisand/blob/master/playbooks/roles/ssh/tasks/main.yml#L2), [configuring an HMAC firewall in OpenVPN to block unauthenticated connections](https://github.com/jlund/streisand/blob/master/playbooks/roles/openvpn/tasks/main.yml#L80), [enabling automatic software upgrades](https://github.com/jlund/streisand/blob/master/playbooks/roles/common/tasks/main.yml#L24), and many other steps.

But yeah, the no-logging-by-design aspect of Streisand is probably going to be your biggest hurdle with Fail2ban.

**Comment by MinimaxHeadroom** [comment]
> which services would you want it to monitor and block?

Primarily the SSH server so I can impose rate limiting.

> the no-logging-by-design aspect of Streisand is probably going to be your biggest hurdle with Fail2ban.

That makes sense. But considering logs aren't kept, what options, if any, might be available for monitoring intrusion attempts on the server?

**Comment by jlund** [comment]
You can easily turn SSH logging back on by modifying the relevant line in the `sshd_config` file.

Disabling password-based authentication means that an intruder would either need to brute-force an entire SSH private key (which is unlikely, to say the least) or possess an OpenSSH 0-day (in which case Fail2ban isn't going to help).

**Comment by jlund** [comment]
Let me know if I can help answer any other questions in this area.
