### ISSUE TITLE
Switch to actively developed windows Shadowsocks

### ISSUE THREAD

**Issue by df-sh** [jlund/streisand#255]
The current shadowsocks project was last updated Sep 20 2015

I switched to https://github.com/breakwa11/shadowsocks-csharp/  for windows builds.

Not sure what these values should be changed to, but the relevant lines are here:

playbooks/roles/streisand-mirror/vars/shadowsocks.yml 
# Windows

shadowsocks_gui_version: "2.5.6"
shadowsocks_gui_filename: "Shadowsocks-win-{{ shadowsocks_gui_version }}.zip"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "https://github.com/shadowsocks/shadowsocks-csharp/releases/download/{{ shadowsocks_gui_version }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "sha256:f061a3885630696637496bcd9e40cacf13ac7b27fb630d16e91aef0ae4011c62"

**Comment by cpu** [comment]
The https://github.com/shadowsocks/shadowsocks-windows/ client we currently mirror is actively developed. There was a release 14 days ago.

I'm going to close this issue. If you still think there is an advantage to mirroring shadowsocks-csharp instead of shadowsocks-windows please open a new issue with your use case.

Thanks!
