### ISSUE TITLE
Unable to setup on Ubuntu 14.04 in Tokyo (Provider: Vultr)

### ISSUE THREAD

**Issue by rennaisance-dangelo** [jlund/streisand#258]
I tried setting up a Streisand server on my Ubuntu VPS, but my setup fails at [Install Streisand common packages]. Am I missing something?

I thought that my issue is similar to Issue #219, but I guess this is not the case. Tried multiple OSes, I am not able to setup on Debian 7/8 and Ubuntu 12.04. On Debian particularly the process fails at setting up l2tp/ipsec. I have edited the inventory files, and ansible.cfg as per the instruction on main page for setting up the server on providers which are not yet supported by streisand officially.

Any help would be greatly appreciated.

**Comment by jlund** [comment]
Ubuntu 14.04 is the only officially supported distribution. It's definitely expected that things would fail on Debian 7 and 8 (and Ubuntu 12.04) which is why the playbook outputs a warning prompt when it detects this situation. Your topic mentions 14.04, but it isn't mentioned in the issue description. Based on your comments in the other thread, I'm assuming the other distributions were tried after the latest Ubuntu failed as well?

The first task that you mentioned is simply attempting to update the APT cache and install some basic packages. If a VPS provider doesn't give you a server that is capable of doing that, there's not much that Ansible or Streisand can do. 

I know that other people have use Vultr successfully in the past, so I'm not sure what could be happening here. I don't have a Vultr account at the moment, but I will see what I can find out.

**Comment by rennaisance-dangelo** [comment]
Hi Joshua,
Yes you are right, I tried the other distros after setup on Ubuntu 14.04 failed. I am not sure why, but when Streisand tries to fetch the files for installing common packages, it fails. I also tried it with my server on US West Coast(where it failed again), so my guess is that it is not a location issue. On Debian 7/8 these steps pass successfully (apt cache and installing common packages), but on Ubuntu I get stuck here. However, on Debian my setup fails when xl2tpd restarts. I also saw a similar issue like that here in issue #171. I will try the resolution mentioned there and report my results on Debian. However, it is weird why it is happening on Ubuntu.

I cloned your repo a while back and I have successfully spun up Streisand servers on Digital Ocean Droplets with it in the past.

P.S. Being a supporter and a fan of your work I wanted to give you a big thumbs up. I would like to contribute in any way I could.

**Comment by rennaisance-dangelo** [comment]
This is the error message I am getting on Ubuntu 14.04. I am attaching it as under:
failed: [xxx.xxx.xxx.xxx] => (item=[u'curl', u'gnupg', u'markdown', u'openntpd', u'python-software-properties', u'qrencode', u'unattended-upgrades', u'wamerican-huge']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["curl", "gnupg", "markdown", "openntpd", "python-software-properties", "qrencode", "unattended-upgrades", "wamerican-huge"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'openntpd'' failed: /etc/openntpd/ntpd.conf: Permission denied\ninvoke-rc.d: initscript openntpd, action \"start\" failed.\ndpkg: error processing package openntpd (--configure):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n openntpd\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr": "/etc/openntpd/ntpd.conf: Permission denied\ninvoke-rc.d: initscript openntpd, action \"start\" failed.\ndpkg: error processing package openntpd (--configure):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n openntpd\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nopenntpd is already the newest version.\nThe following package was automatically installed and is no longer required:\n  libopts25\nUse 'apt-get autoremove' to remove it.\n0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.\n1 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up openntpd (20080406p-7) ...\nStarting openntpd: ", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "openntpd is already the newest version.", "The following package was automatically installed and is no longer required:", "  libopts25", "Use 'apt-get autoremove' to remove it.", "0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.", "1 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up openntpd (20080406p-7) ...", "Starting openntpd: "]}

**Comment by jlund** [comment]
It looks like the current Vultr image for Ubuntu 14.04 might be in a broken state for APT updates. This is an APT error, not a Streisand error.

Thanks for the kind words. I will see about making a Vultr account so that I can troubleshoot the issue more thoroughly and create a support ticket to fix their broken image (if this is indeed what is happening).

**Comment by rennaisance-dangelo** [comment]
Thank you for your support. Yes you are right about it being an APT error, but upon manually updating the cache using 'apt-get update', I do not get any error on the Vultr VPS. In fact I have manually setup l2tp/Ipsec as well as shadowsocks without any hindrance. I will also open a support ticket with Vultr at my end to dig deeper into the cause.

**Comment by xlphs** [comment]
I ran into the same problem on Vultr today, openntpd was not able to start because of conflict with ntp. Refer to [this bug report](https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061) for workaround, the relevant lines are:

```
apt-get install openntpd -y
apt-get purge ntp -y
service apparmor restart
service openntpd restart
```

You just need to ssh into the server yourself and execute those commands.

**Comment by rennaisance-dangelo** [comment]
Thank you very much. This worked flawlessly.

**Comment by rennaisance-dangelo** [comment]
Closing the issue!

**Comment by jlund** [comment]
This workaround should no longer be necessary!
