### ISSUE TITLE
Rsyslog Fails to Restart on Debian 8

### ISSUE THREAD

**Issue by antagonismorg** [jlund/streisand#259]
I am attempting to install a DigitalOcean Debian 8 instance. When run the playbook, I get the following error message:

> TASK [l2tp-ipsec : Copy the rsyslog config file that prevents incoming L2TP/IPsec traffic from being logged by completely filtering out all messages from pppd, charon, and xl2tpd.] ***
> changed: [streisand.antagonism.org] => {"changed": true, "checksum": "2dad15827caff71023db23d6465f369cb58586c5", "dest": "/etc/rsyslog.conf", "gid": 0, "group": "root", "md5sum": "22817df4e7b8b5346ce1e49c80f8267e", "mode": "0644", "owner": "root", "size": 2847, "src": "/root/.ansible/tmp/ansible-tmp-1456106651.93-148289619225152/source", "state": "file", "uid": 0}
> 
> TASK [l2tp-ipsec : Restart rsyslog to apply the new configuration] *************
> fatal: [streisand.antagonism.org]: FAILED! => {"changed": false, "failed": true, "msg": "Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.\n"}
> 
> PLAY RECAP *********************************************************************
> streisand.antagonism.org   : ok=54   changed=10   unreachable=0    failed=1  
> 

It appears the service is having an issue with lines 61-64.

> Next token is token FUNC ()
> 6724.427708668:main thread    : Called LogMsg, msg: error during parsing file /etc/rsyslog.conf, on or before line 61: syntax error on token 'stop'
> Error: popping nterm expr ()
> Stack now 0 1 18
> Error: popping token IF ()
> Stack now 0 1
> Error: popping nterm conf ()
> Stack now 0
> Cleanup: discarding lookahead token FUNC ()
> Stack now 0
> 6724.428105661:main thread    : Called LogMsg, msg: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf'.
> 6724.428225055:main thread    : GenerateLocalHostName uses 'streisand'
> rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)

If I comment out these lines, the service restarts fine.

I am running stock rsyslog

> root@streisand:~/git/streisand# rsyslogd -v
> rsyslogd 8.4.2, compiled with:
>         FEATURE_REGEXP:                         Yes
>         GSSAPI Kerberos 5 support:              Yes
>         FEATURE_DEBUG (debug build, slow code): No
>         32bit Atomic operations supported:      Yes
>         64bit Atomic operations supported:      Yes
>         memory allocator:                       system default
>         Runtime Instrumentation (slow code):    No
>         uuid support:                           Yes
>         Number of Bits in RainerScript integers: 64
> 
> See http://www.rsyslog.com for more information.

**Comment by antagonismorg** [comment]
I confirmed it specifically is related to lines 61-63.

**Comment by antagonismorg** [comment]
Apparently, the if statements need a then as well. @jlund how would you like me to handle this in a PR? Should I code it modern versions of rsyslog or should I check for the rsyslog version and paste accordingly?

**Comment by jlund** [comment]
Those lines deal with filtering out the L2TP/IPsec connection information that would otherwise get logged.

The provided config file for rsyslog works with the version (7.4.4) that ships with Ubuntu 14.04. Ubuntu 14.04 is the only supported Linux distribution, and we would want to avoid making changes that do any of the following:
* Break compatibility with rsyslog on Ubuntu 14.04.
* Cause log entries to stop being filtered on Ubuntu 14.04.
* Clutter the codebase with conditionals that are unrelated to the supported distribution.

If we can accomplish all of the above with some simple changes, that's a PR that I would be happy to review :)

It's important to me to only target a single distribution. It's already daunting to keep up with the support and development overhead that comes from tracking down root causes across such a diverse set of daemons and providers. That task becomes exponentially more difficult if we introduce additional distributions into the mix.

The future base distribution for Streisand will either be Debian 8 or Ubuntu 16.04. I plan on making that decision shortly after 16.04 has been released. Debian 8 was considered late last year instead of Ubuntu 14.04 as a natural replacement for Debian 7. It was actually my first choice. Sadly, there were _lots_ of problems related to systemd on Debian 8 that have since (hopefully!) been resolved. For instance, the OpenVPN service would not restart correctly without multiple attempts.

There are likely many, many other places where things are broken on Debian 8 aside from the two issues that you have filed so far. Just out of curiosity, why aren't you running this on Ubuntu 14.04? DigitalOcean is one of the supported providers; it would be even easier.

**Comment by antagonismorg** [comment]
Personal preference. If you have a list of Debian 8 issues, I would be happy to help explore and possibly resolve those issues.
