### ISSUE TITLE
Encryption level cleanup?

### ISSUE THREAD

**Issue by lazerhawk** [jlund/streisand#281]
Running a recent streisand box through the following two probing services

https://www.ssllabs.com/ssltest/
https://discovery.cryptosense.com/

turns up some issues. 

Is SSL3 supposed to be enabled for compatibility purposes, considering the self-sign cert is SHA-256?
Are low DF bits and SHA-1 also supposed to be there for compatibility?
Considering compatibility issues, could there be an install option for low end clients needing weakend ciphers, so one can opt out of using weaker settings?

This TLS guide for Nginx seems like a good reference
https://gist.github.com/kennwhite/f63c5366b1e63f01f6c8

CloudFlare also has a Nginx security reference, but they deliberately weaken some parts for compatibility purposes
https://github.com/cloudflare/sslconfig

It also seems possible to separate server SSL certs from client certs by designating a different CA (streisand internal CA for client), so perhaps consider an option to retrieve a LetsEncrypt SSL server certificate for Nginx itself, which may be an acceptable risk for some users?

**Comment by hydrandt** [comment]
Let's encrypt: The problem I see here is that you first need to point your domain name to the server IP in order to obtain the certificate. You can not do this in advance, as Streisand spins up a new server with a new IP for you. 

One way to do it: In the facts gathering phase, tell user about the possibility to use let's encrypt in case she has a domain she'd like to use to access the server, and if so, what is it. After spinning up the instance, show its IP to the user and ask her to modify the DNS record, and press enter to continue, then check whether this is 90s after the spinup (waiting for ssh) and continue.

Then the nginx certificate obtaining would be one of the last steps (so the dns changes have time to propagate), streisand would try to get it, if unsuccessful, user could choose to wait a bit and try again, or generate a self-signed certificate.

What do you think? I could try to implement this.

**Comment by lazerhawk** [comment]
Considering the limitations of LetsEncrypt that might work, but the DNS propagation issue will trip people up. Perhaps just before the certificate retrieval stage, show a simple DNS probe check status that loops every 5 seconds to see if the DNS name is ready while waiting for user input to proceed with LetsEncrypt or bail out and use self-signed?

**Comment by jlund** [comment]
The Nginx configuration and DH parameter generation steps were [recently updated](https://github.com/jlund/streisand/commit/d5120b8bbbee340ac247a155156e7fab9c0bbbe9) and discussed in issues #279 and #179. SSLv3, weak DH parameters, and the cipher suite preference order within the Nginx vhost have all been enhanced. I used the latest recommend Nginx configuration from Mozilla.

Notably, this didn't actually change anything at all for users of modern browsers which already disable SSLv3 on the client side (and have for nearly two years) and which choose strong cipher suites by default. It has been just over a week now, and I'm really happy that no user complaints resulted from this change. Despite the continued focus on SSLv3 by all of the SSL scanners, removing it from clients pretty much solved the problem a long time ago.

Moving to Ubuntu 16.04 as the base foundation will enable lots of good stuff in the OpenSSH daemon like ChaCha20, etc. I plan on improving that configuration once 16.04 is released and widely available. I'm less concerned about the stunnel warnings that show up in the Cryptosense report because stunnel is used merely as an obfuscation layer for OpenVPN, and OpenVPN should be secure on its own. Still, the move to Ubuntu 16.04 will also update the stunnel daemon too.

I think that LetsEncrypt and support for custom domain names would add significant complexity to the setup process and wouldn't really result in a more secure configuration. Self-signed certificates are just as strong, and installing them is easier for the average user than obtaining a custom domain name and modifying its DNS records. LetsEncrypt does not support issuing SSL certificates for a bare IP, and giving a brand-new Streisand server a permanent domain during the setup process arguably sends the wrong message. I think that it's best for people to treat their VPN servers as disposable and easily replaced, which is why it was so important to automate the process :)

I appreciate the feedback! I definitely want Streisand to be as secure as possible.

**Comment by lazerhawk** [comment]
Thanks for the heads up on the changes linking to the move to the new ubuntu LTS.

Self signed cert would be a metadata marker for the stunnel connection, thus I thought if the aim is obfuscation/masking then a valid cert triggers less alarms, and is more likely to penetrate an egress filtering firewall/UTM (though some of the ones that pass valid certs by default are starting to block LetsEncrypt as a suspicious CA...) so that would help end users. The basic disposable stance being the primary design aim, I can appreciate why tying to a real domain is troublesome.

That said, for reference FreeDNS at afraid.org has for a long time allowed users to "borrow" other people's domains from a public pool of DNS names with your choice of hostname, so random domains are feasible to support the disposable goal.
