### ISSUE TITLE
How do I update ssh?

### ISSUE THREAD

**Issue by umbrageous** [jlund/streisand#283]
ssh is working fine, but the terminal-type screen on opening a tunnel says:-

19 packages can be updated.
0 updates are security updates.

*** System restart required ***

Do I need to do this? Can anyone tell me, please, how I set about updating ssh in Streisand?

Thanks!

**Comment by jlund** [comment]
If you would like to apply these updates, you can run `sudo apt-get update` and `sudo apt-get upgrade`. To restart your server, a `sudo reboot` is usually sufficient.

Security updates get installed automatically thanks to the unattended-upgrades package, which is why that number is zero.

I hope this helps!
