### ISSUE TITLE
AWS security group is wide open

### ISSUE THREAD

**Issue by johnjeffers** [jlund/streisand#312]
Wondering why the AWS security group created by the Ansible script adds a rule that allows any traffic from anywhere.  See attached screen shot.

<img width="948" alt="screen shot 2016-06-02 at 2 57 20 pm" src="https://cloud.githubusercontent.com/assets/11821214/15760852/704b2578-28d2-11e6-8c5c-7693fd914d3e.png">

**Comment by jlund** [comment]
Yeah, so, it doesn't. It's not in the code:

https://github.com/jlund/streisand/blob/master/playbooks/roles/ec2-security-group/tasks/main.yml

If that's happening, it's definitely a bug and not the intended behavior. The UFW firewall would still be blocking everything else though. Still, I'll get this fixed if and when I can reproduce it.

**Comment by johnjeffers** [comment]
Cool, thanks. I will run the script in another region and see if I can reproduce it myself. Thanks for the quick response.

**Comment by johnjeffers** [comment]
I just reproduced the behavior in US West (Oregon). Wide open SG after playbook completion. Let me know if you want me to try anything else.

**Comment by jlund** [comment]
Turns out I _totally_ misunderstood what `proto: "all"` meant. I was under the impression that this was shorthand to simultaneously add a rule for TCP and UDP, but what it does instead is make the problematic rule that you identified above while ignoring the port number arguments. So it was in the code after all :)

Thank you very much for the bug report and for your help troubleshooting the issue.
