### ISSUE TITLE
Feature: Support/Verify Cygwin, and/or MinGW, and/or Chocolatey 

### ISSUE THREAD

**Issue by starrychloe** [jlund/streisand#315]
Please support or verify it works with Cygwin and/or MinGW and/or Chocolatey on Windows.
https://cygwin.com/
http://mingw.org/
https://chocolatey.org/

**Comment by cpu** [comment]
I agree with @chimpchimp's assessment. At this point I don't think anyone has the resources to try and support running Streisand on Windows. If Ansible support on Windows improves (or has improved already since this issue was created!) then it might be worth revisiting. Feel free to reopen if you believe this is the case. Thanks!
