### ISSUE TITLE
Assign Elastic IP to AWS EC2 instances

### ISSUE THREAD

**Issue by johnjeffers** [jlund/streisand#320]
For EC2 instances with public IP addresses, it’s usually desirable to assign an Elastic IP to the instance to ensure that the public IP does not change.

Without an Elastic IP, the public IP address will change any time the instance is stopped or restarted. If the public IP of the instance changes, it will break all sorts of things.

This update will associate an Elastic IP address to the EC2 instance immediately after instance creation, and assigns the Elastic IP to the streisand_ipv4_address variable for use in the rest of the playbook.

EDIT: This is now a pull request.

https://github.com/jlund/streisand/pull/323

**Comment by cottmann** [comment]
This addresses the problem of certificates not being valid after the IP changed (ie, instance stopped and started again). It does so with additional cost (for keeping the Elastic IP around when the server is down), and does not help for multi-region deploys (where you might want to use the same certificate). 

My preference is to generate the server certificates with CN=vpn.example.com instead of an IP  and then let the instance use Route 53 to set a CNAME to itself (hope to get around to implement that in the next days). 

So why not make it a choice? 
1. Default as is -- use the IP set by AWS to generate the certificate
2. Use elastic IP (as above)
3. Use DNS name (vpn.example.com)

**Comment by kydan** [comment]
The option of a DNS name for the sll cert would be excellent for my
situation, as I switch ip's frequently.
On Jun 5, 2016 12:40 AM, "Tobias Cottmann" <notifications@github.com> wrote:

This addresses the problem of certificates not being valid after the IP
changed (ie, instance stopped and started again). It does so with
additional cost (for keeping the Elastic IP around when the server is
down), and does not help for multi-region deploys (where you might want to
use the same certificate).

My preference is to generate the server certificates with CN=vpn.example.com
instead of an IP and then let the instance use Route 53 to set a CNAME to
itself (hope to get around to implement that in the next days).

So why not make it a choice?
1. Default as is -- use the IP set by AWS to generate the certificate
2. Use elastic IP (as above)
3. Use DNS name (vpn.example.com)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jlund/streisand/issues/320#issuecomment-223765382>, or mute
the thread
<https://github.com/notifications/unsubscribe/ACE5KFCsLI1grWGfIVavc_WFmHji-DLWks5qIaqRgaJpZM4IuDTe>
.

**Comment by johnjeffers** [comment]
If the point of this project is privacy, why would you want a domain name attached to your public IP?

**Comment by cottmann** [comment]
@johnjeffers - Depends on your use case of course, which is why I suggest to make it a choice. 

I want to have a VPN when using WLAN while on the road. It won't run all the time, and the server might run in different AWS regions, depending on my physical location. Using my own DNS record doesn't matter, because the only thing a snooper on the WLAN can see is that I connect to it, not the traffic itself. But it keeps the server certificate valid, even when switching locations. 

Elastic IP is a great solution when the server remains in the same region. But it cannot be moved across regions, so that won't work for me.

**Comment by johnjeffers** [comment]
@cottmann Understood, but if all you want is a VPN endpoint that can live in different AWS regions and use the same server certificate, then this project seems like overkill for your use case. [OpenVPN Access Server](https://openvpn.net/index.php/access-server/overview.html) is simple to install, free for up to 2 users, and relatively easy to administer. I even have an Ansible playbook for a straighforward OpenVPN AS server install I would be willing to share.

I certainly can't speak to @jlund's intentions behind this project, but it occurs to me that associating a DNS record that can be easily traced back to its owner defeats at least some of the privacy that Streisand is designed to provide.

That said, I could be completely off-base here. I'm interested to hear @jlund's take on it.

**Comment by cottmann** [comment]
@johnjeffers -- Agree, Streisand is probably overkill for me. But my experience with other solutions is that they are really painful (or impossible) to set up. In contrast, Streisand just worked without any tweaks. So I am quite happy with it. 

Would also be interested to hear @jlund 's take.

**Comment by timXTM** [comment]
@johnjeffers Sometimes access is all that is needed, not strictly privacy. For expample, the OpenVPN Access Server is sensored by China once it's up and running. But, if you were using Streisand's stunnel implemntation and connecting to a domain name, you'd have no problems.

**Comment by jlund** [comment]
For this issue, I was planning on making automatic EIP assignment for new EC2 instances part of the default behavior, and I'm grateful to @johnjeffers for making it happen. Not having this in place was causing a lot of problems when an instance had to go through a stop/start cycle and came up with a completely different address. It has been in my backlog for a while.

Regarding the rest of the discussion, the primary goal of the project is to help people bypass censorship as seamlessly as possible. However, I am also passionate about privacy and anonymity as well. That's why I included support for Tor Bridges from day one.

I think the discussion here is really interesting, and it seems closely related to #319 too. It's clearly a common pain point for users in China to have to swap their IP addresses on a somewhat regular basis and deal with the configuration changes that necessarily follow. I want to do something to make that easier.

At the same time, I also would like people to see their servers as ephemeral and easy to replace. I'm not sure yet how to walk the line between these two worlds, but I think we can figure it out. Let's continue the discussion in #319.
