### ISSUE TITLE
Enabling ssh into server(s) on another Linux machine...

### ISSUE THREAD

**Issue by muamma** [jlund/streisand#328]
I wonder whether someone could point me in the right direction here.

I run Ubuntu in a VM on a (Windows) machine) from which I ssh into my server(s): H1.

I also have another machine which runs Ubuntu [H2], and I want to be able to ssh into my server(s) from that machine too.

1) Do I try to copy my id_rsa key from H1 to H2, and if so how?

2) Or do I generate a new (public and private) key on H2, and presumably copy the public element to the server(s)? Again, any pointers would be appreciated.

One further question. From H1, there is no need to enter a password to ssh into the server(s). How do I ensure that I don't have to put a password in every time when I use H2 for this purpose?

Thanks!

**Comment by alimakki** [comment]
Assuming that you mean you want to log into H2 via H1, you would do the following from H1:

ssh-copy-id user@hostname.example.com

H2 should not ask for your password after running the above.

**Comment by muamma** [comment]
@alimakki, thanks, but (being new to this - mea culpa!) I am a little confused, and so I may have confused you too.

Let's call my first Ubuntu Linux computer, from which I access server(s) S1, S2, etc... L1. My other Ubuntu Linux computer, which I want to use also for ssh access to S1 etc, is... L2.

I want to access S1, S2, etc by ssh from L2, as well as from L1. But independently.

I was just wondering what the steps might be, vis-a-vis L1 and L2, to gain ssh access to S1 etc from L2, without the need for a password.

Presumably this has to involve both a public key, which resides on S1, etc (as well as L1?), and a private key, which is currently just on L1. I guess my question is: how do I either copy the private key on L1 onto L2, or generate a new private key on L2 which can relate to or connect to the public key on S1 etc.

Or have I got this completely wrong? Thanks...!

**Comment by db48x** [comment]
A complete explanation of ssh key authorization is a bit much to type into this box, but suffice it to say that both machines have one or more key pairs consisting of a public key and a private key.

The guiding principle is that the private key must always be kept secret while the public key can be known to all.

You can add the text of one or more public keys to ~/.ssh/authorized_keys to tell sshd to encrypt a challenge using these keys and send it to whoever connects. Anyone who can decrypt the challenge is allowed to log in to this account without a password. The challenge can only be decrypted by the corresponding private key, so only you can log in.

The answer to your question then, is that you must have on L2 the same key pair that you have on L1, or that you must have L2's public key in the .authorized_keys file on the server. You can choose either one. Remember that if someone else gains access to the private key then your security is blown (same as if they found out your password), so if L2 is actually owned by your employer or something then you definitely want it to have a separate key pair.

The default filename for the private key is ~/.ssh/id_<keytype>, where keytype is either rsa, dsa, ecdsa, or ed25519. Of course you can generate any number of key pairs that you like, (so that you can use them for different purposes), so yours might have a different name.

The ssh-copy-id program will copy the public key from your local machine to a remote machine, adding it to the remote machine's ~/.ssh/.authorized_keys file for you. If you copy your existing key pair to another machine, however, you can skip it as that key pair's public key is already authorized.

You should check out the ssh manual, particularly the page about configuring ssh, for all of the details. Run 'man ssh_config' to see it.

**Comment by muamma** [comment]
@db48x, that's really very helpful indeed. Thank you. I shall now go and explore the options!

**Comment by cpu** [comment]
It seems like there has been lots of useful information shared in this issue already. Thanks everyone! 
Since this isn't a question directly related to Streisand I'm going to close this issue. Please feel free to open a new issue if you have follow up questions about Streisand.
