### ISSUE TITLE
.ovpn has the route statement that causes the openvpn warning

### ISSUE THREAD

**Issue by yurivict** [jlund/streisand#329]
I am not sure if this route statement is required, but for whatever reason OpenVPN does the same again and prints warning.

See the OpenVPN bug https://community.openvpn.net/openvpn/ticket/688

**Comment by alimakki** [comment]
It looks like from the logs you posted OpenVPN is adding the route twice.

I think it may be because the server configuration has a directive to redirect the gateway:

<pre>
push "redirect-gateway def1"
</pre>

As well as the client having:

<pre>
route x.x.x.x 255.255.255.255 net_gateway
</pre>

which seem to conflict.

Can you try removing the route directive from your client to see if the warning disappears?

**Comment by cpu** [comment]
There hasn't been a reply to the question posed on this ticket over a year ago. Closing as stale. Please open a new issue if you're still having this problem with the tip of master & a fresh server provisioned with Streisand. Thanks!

**Comment by nikksno** [comment]
Hi there
nmcli on ubuntu 16 is complaining about the third argument of ```route``` *not* being an IPv4 on the client side.
I'll try removing it and report back.
Any ideas?

Thanks
