### ISSUE TITLE
Inatall: Fatal failure while apply rsyslog start on debian jessie

### ISSUE THREAD

**Issue by huggenknubbel** [jlund/streisand#346]
i got this message: 

```
TASK [rsyslog : Restart rsyslog to apply the new configuration] ****************
fatal: [5.189.162.118]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Stopping rsyslog.service, but it can still be activated by:\n  syslog.socket\nJob for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.\n"}
```

if i try to start the service on the destinationserver manualy i got this: 

 ```
systemctl status rsyslog.service
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled)
   Active: failed (Result: start-limit) since Thu 2016-06-16 20:55:45 CEST; 3min 47s ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
  Process: 15472 ExecStart=/usr/sbin/rsyslogd -n (code=exited, status=1/FAILURE)
 Main PID: 15472 (code=exited, status=1/FAILURE)

Jun 16 20:55:44 hirsch.one systemd[1]: rsyslog.service: main process exited, code=exited, status=1/FAILURE
Jun 16 20:55:44 hirsch.one systemd[1]: Failed to start System Logging Service.
Jun 16 20:55:44 hirsch.one systemd[1]: Unit rsyslog.service entered failed state.
Jun 16 20:55:45 hirsch.one systemd[1]: rsyslog.service start request repeated too quickly, refusing to start.
Jun 16 20:55:45 hirsch.one systemd[1]: Failed to start System Logging Service.
Jun 16 20:55:45 hirsch.one systemd[1]: Unit rsyslog.service entered failed state.
Jun 16 20:55:45 hirsch.one systemd[1]: rsyslog.service start request repeated too quickly, refusing to start.
Jun 16 20:55:45 hirsch.one systemd[1]: Failed to start System Logging Service.

```

**Comment by jlund** [comment]
Debian Jessie is not a supported distribution at this time. This is only one of several problems that you'll encounter when you're not using Ubuntu, which is why the playbook outputs the warning that it does when it's run against something else.

Ubuntu 16.04 (Xenial) will soon become the base distribution, and I have already started working on that upgrade. I don't have the bandwidth to support more than one foundation at a time, and Ubuntu is far more ubiquitous across hosting providers. I wrote a [little bit more detail about my thought process in this area](https://github.com/jlund/streisand/issues/54#issuecomment-214967907) around a month ago.

It's likely that some of the work related to 16.04 will also benefit Debian, but if Streisand happens to start working on Jessie it will still likely be in an unofficial and unsupported form.

Thanks for the feedback!
