### ISSUE TITLE
Mirror Tunnelblick for OS X failed

### ISSUE THREAD

**Issue by pguizeline** [jlund/streisand#354]
Hello, I'm trying to setup a Streisand server over at DigitalOcean and got this message. It's probably because there's a newer version of the file or incorrect path.

```
TASK [streisand-mirror : Mirror Tunnelblick for OS X] **************************
fatal: [188.166.231.249]: FAILED! => {"changed": false, "dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://tunnelblick.net/release/Tunnelblick_3.6.3_build_4560.dmg"}
```

Is it possible to fix this after Streisand is deployed? Or I need to do a full install from scratch?

Thanks in advance for the help!

**Comment by bakkus** [comment]
Getting the same error:

TASK [streisand-mirror : Mirror Tunnelblick for OS X] **************************
fatal: [91.247.228.19]: FAILED! => {"changed": false, "dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://tunnelblick.net/release/Tunnelblick_3.6.3_build_4560.dmg"}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***

**Comment by jlund** [comment]
This has now been resolved (thanks, @alimakki!).

@pguizeline This shouldn't affect the running server at all. The file that got skipped in the mirroring process can be downloaded separately.
