### ISSUE TITLE
Last version that runs on Ubuntu 14.04?

### ISSUE THREAD

**Issue by accolon** [jlund/streisand#387]
Due to current issues with my hoster, I'm not yet able to run Ubuntu 16.04.

I want to setup a new Streisand instance for travel purposes, but due to the recent commits I'm not able to find out what the last version to install on 14.04 is.

Could you please point me in the right direction or (even better) tag the last Streisand version that installs on 14.04? Thanks!

**Comment by alimakki** [comment]
the current Master branch is what you want.

**Comment by accolon** [comment]
Nope, the Master branch contains the 16.04 specific changes (which do not work on 14.04 since there are new dependencies).

**Comment by jlund** [comment]
Master was upgraded to 16.04 over the weekend. I tried to wait until Xenial support was as widespread as possible, but some providers are still lagging.

This should get you what you need, @accolon. This was the last commit to master before the `xenial` branch got merged:
`git checkout bfb6db1e545e56973bc715acde8afafd007c78a1`

If it makes you feel any better, my favorite local ISP still hasn't updated their Ubuntu VPS images yet. I'm doing in-place upgrades on new servers in order to bring them into the present, but I'm hoping they make it easier soon :)
