### ISSUE TITLE
Deployed server not coping with IP change

### ISSUE THREAD

**Issue by TychoSchenkeveld** [jlund/streisand#433]
I deployed 2 streisand servers on Scaleway that stopped working after a while..

Eventually I figured out that it's because of the way Scaleway routes its traffic. The box itself does not see its external IP. It just has a dynamic internal IP in the 10.x.x.x range, which actually changes dynamically when you temporary switch your server off. They route the external IP traffic to this internal IP.

Some of the config files (x2ltp, shadowsocks, sslh..) have the eth0 interface IP hardcoded after deployment and this stops it from working because they can no longer bind to the interface after its address has changed.

Would it be possible to change the config files so they bind to the interface some other way? Such as interface name or MAC? There seems to be no way within scaleway to fix the internal IP the server gets.

Or otherwise perhaps to have a script that can re-generate the config files that contain fixed IPs?

**Comment by cpu** [comment]
Hi @TychoSchenkeveld,

At this time we're not able to support Scaleway as a provider, or its network interface peculiarities. I would welcome non-intrusive PRs if you wanted to try and improve support yourself. 

> Or otherwise perhaps to have a script that can re-generate the config files that contain fixed IPs?

@nickolasclarke and a few other folks have been working on aspects of this and I suspect that in the future there will be a concerted effort to try and support re-profiling a server with a new IP. No solid plans or ETA at this point.

I'm going to close this issue for now since it is Scaleway based. Thanks for understanding!
