### ISSUE TITLE
Many Connectivity Issues

### ISSUE THREAD

**Issue by Ev3y** [jlund/streisand#436]
- OpenVPN (direct) on Windows 10 over Ethernet will occasionally lose connection

- OpenVPN (direct) on Windows 10 over Ethernet will occasionally have ping spikes (200-1000 ping)

- OpenVPN (direct) on Android (using OpenVPN Connect instead of OpenVPN for Android) over WiFi will occasionally lose connection, showing to be stuck at "assigning IP address" in the notification bar and showing "disconnected" in the app

- L2TP/IPsec on Chromium (Chrome OS) over WiFi will occasionally fail to connect for about 5 minutes

I'm running Streisand on a standard DigitalOcean server, and I don't see others commenting about issues like this. Might this have something to do with how the network I'm on treats these connections? How should I go about fixing these issues?

**Comment by cpu** [comment]
> Might this have something to do with how the network I'm on treats these connections? How should I go about fixing these issues?

My first suggestion would be to try and measure the network performance directly from your Streisand server and then again from your local machine to the Streisand server. You might find [mtr](https://www.digitalocean.com/community/tutorials/how-to-use-traceroute-and-mtr-to-diagnose-network-issues#how-to-use-mtr) a useful tool for this. Hopefully doing so would allow you to isolate if the problem was on your side of the network or the Streisand server's. You may also want to experiment with running a Streisand node in a non-Digital Ocean provider (e.g. EC2) and see if OpenVPN performance is still poor.

**Comment by ev3y2** [comment]
Thanks for the advice, though I haven't had these issues in a while. If I do I'll be sure to report back here. I would close the issue (at least for now) but I can't log into my account (Ev3y).

**Comment by cpu** [comment]
@ev3y2 Thanks for the update - I'll go ahead and close this issue for you. Take care.
