### ISSUE TITLE
Feature Request: Add destruction capabilities

### ISSUE THREAD

**Issue by MartinLeedotOrg** [jlund/streisand#475]
For those unfamiliar with AWS, removing the created instance might be a bit tricky, this could be automated.

I've created a destroy branch at: https://github.com/MartinLeeUK/streisand/tree/destroy

Before I submit a pull request, is this needed? Is there a better approach?

**Comment by bryan4887** [comment]
I agree; this would be a very convenient feature.

**Comment by cpu** [comment]
@MartinLeedotOrg Is this request specific to AWS or a general ask? I'd like to update the title if it is AWS specific.

**Comment by lazerhawk** [comment]
Are you suggesting some sort of internal self destruct feature, where if a condition specified at creation is reached, the instance becomes unavailable to VPN users and prepares to remove internal data in some manner?

A timer based condition would be interesting, perhaps a deadman's switch? This ties into the issue of how old an instance should be, such as an instance that was left running for a long time using an Ubuntu LTS instance that may have reached end of OS support (LTS). See #513 

Other conditions, like watching a version management file or canary file (but no access due to 404 might end up being a DoS)

There is the two main issues of how far should a self-destruct go though.

1. How far to destroy internally; removing assorted VPN keys and logs, write zeros to freed space, but perhaps leave the ssh keys for connectivity for final remediation?

2. How far to destroy externally; stopping and removing the VM instance, but this may require cached cloud provider credentials if attempting to execute internally from the VM which is a major leakage issue. Doing it externally would require the original creation source OS to schedule something like a cron job or similar, but again the caching of credentials becomes problematic. Would this start to become AWS IAM tricks, like deploying a single instance management user with self destruct capability for only that instance?

**Comment by MartinLeedotOrg** [comment]
So, I was more thinking of just extending the script to tear down instances once you're done with them.  It's not intuitive in AWS, especially for a novice.

As I said, check out the feature branch at https://github.com/MartinLeeUK/streisand/tree/destroy - I've already made the playbook and role for AWS.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand/issues/475
