### ISSUE TITLE
Finish implementing WireGuard support

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#480]

**Comment by jlund** [comment]
Done! I'm excited to hear what people think after they try it. It's in a completely different league in terms of performance, design, simplicity, and security. It's the best choice for Linux users even at this early stage of development, in my opinion.

**Comment by SquirrelCoder** [comment]
Hey jlund,

I want to setup WireGuard on my Ubuntu server too, is there any guide for setting up WireGuard?
I have followed the official documentation, but I lost, I don't know, how to config the server, and the client, and which config is for the server and which for the client.
I read your configs too, but couldn't understand.
Is it possible for you, to guide me, or even mention some tutorial website?

Thanks

**Comment by jlund** [comment]
If you use Streisand to set up a new server, it will install and configure WireGuard. It also generates custom configuration instructions as well. Let me know if you have any questions!

**Comment by SquirrelCoder** [comment]
Thanks a lot for your fast response.
Actually, I don't use Streisand, because it runs on Ubuntu, and my main server (which I use as VPN) runs CentOS 7. I implement each protocol individually and manually on my server, and till now, everything you have implemented in your VPN config, I have implemented in my CentOS server, though I can't install WireGuard.
Unfortunately there is no tutorial on the internet, and I am not even sure if WireGuard runs even in a Server/Client scenario (my client's IP is dynamic), and for this scenario, I could not find any HowTo.
I wanted to know, if you could guide me, or even point me to some website, which has the WireGuard Server/Client Scenario HowTo.

Thanks a lot.
