### ISSUE TITLE
install on ubuntu 16.04 64bit error

### ISSUE THREAD

**Issue by ookangzheng** [jlund/streisand#496]
<img width="962" alt="screenshot 2017-02-01 23 57 43" src="https://cloud.githubusercontent.com/assets/6301735/22530084/5b3c8712-e8da-11e6-876a-66b5e23f2031.png">

**Comment by jlund** [comment]
On a headless system (like a server) the `xdg-open` command is not going to be available. But that's OK, because all this step is trying to do is open the HTML instructions in a browser. You can also download those instructions using `scp` or `sftp`. They'll be in the `~/streisand/generated-docs` directory as `streisand.html` on the server from your screenshot.

So you could run something like this from your laptop to grab the file: `scp root@ip-address-of-the-server-from-your-screenshot:~/streisand/streisand.html .` Then you can open that file in your browser.

**Comment by cpu** [comment]
Going to close this issue - the error is expected and @jlund has supplied workarounds. Thanks!
