### ISSUE TITLE
Is there any way I can change the loging username/password of streisand.html?

### ISSUE THREAD

**Issue by psionic12** [jlund/streisand#511]
it's to hard to remeber.

**Comment by sjug** [comment]
Create a new [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) file at `/etc/nginx/htpasswd`

**Comment by cpu** [comment]
Closing this issue - @sjug's answer is correct if you wish to do this as a one-off change. If you need help feel free to reopen this issue!

**Comment by panzihan** [comment]
Hi guys
I tried to configure Nginx in accordance with this tutorial：<[How To Set Up Password Authentication with Nginx on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04)>, but the username and password did not change。I do not know where it is wrong。@sjug

**Comment by cpu** [comment]
@panzihan That tutorial is for Ubuntu 14.04 and Streisand creates a 16.04 instance. You also don't need to do the initial password authentication setup since Streisand does that too! The only thing you need to do is update/replace the `/etc/nginx/htpasswd`. You can do this the [same way Streisand does](https://github.com/jlund/streisand/blob/b946974596c3af64a5099920cc5ff42268388240/playbooks/roles/streisand-gateway/tasks/main.yml#L58:L61) by running (as root on the server):

`htpasswd -b -c /etc/nginx/htpasswd streisand "my-new-password-here"`

and then make sure to reload nginx by running (again as root):

`service nginx reload`.

If this doesn't work for you I suggest that you try to find a general purpose Linux server administration forum that could help - it isn't really a Streisand question. The [ubuntu forums](https://ubuntuforums.org/) or [Server Fault](https://serverfault.com) are two good places to start.

Hope that helps!

**Comment by walkerwzy** [comment]
> Create a new [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) file at `/etc/nginx/htpasswd`

I found the file `gateway-password.txt` contains my passowrd, not the `htpasswd`, is there something misunderstand?
