### ISSUE TITLE
PuTTY could not be mirrored.

### ISSUE THREAD

**Issue by mystfox** [jlund/streisand#525]
Relevant part of the output:
```
TASK [streisand-mirror : Mirror the PuTTY files and signatures] ****************
failed: [188.166.84.21] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe"}
failed: [188.166.84.21] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg"}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [188.166.84.21]
```

And checking in browser, said link does indeed 404.

**Comment by kehao95** [comment]
Same problem here.
`
TASK [streisand-mirror : Mirror the PuTTY files and signatures] ****************
failed: [188.166.53.25] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe"}
failed: [188.166.53.25] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg"}
`
While building on DigitalOcean in SFO1 data center.

**Comment by FlyingDiver** [comment]
One more...
TASK [streisand-mirror : Mirror the PuTTY files and signatures] ****************
failed: [162.243.27.178] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe"}
failed: [162.243.27.178] (item=http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg) => {"dest": "/var/www/streisand/mirror/ssh", "failed": true, "gid": 33, "group": "www-data", "item": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe.gpg"}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***

**Comment by jlund** [comment]
Thanks for the bug reports! A fix for this was just merged so the twenty-second pause is no longer necessary and the file gets mirrored correctly. I'm excited that PuTTY has added TLS to their download location in addition to the GPG signature checking that was already in place.
