### ISSUE TITLE
Ability setup on own server.

### ISSUE THREAD

**Issue by ahirmayur** [jlund/streisand#54]
Is it possible to install and run streisand on own server i.e. private-cloud running Ubuntu 14.04.1?

**Comment by wicknet** [comment]
A quick ping to check if supporting a more modern, mainstream and "pure" upstream distro like Debian 8 is under consideration? Streisand works well on Ubuntu 14.04, but Trusty is showing it's age, to say nothing of it's quirks.

**Comment by jlund** [comment]
Ubuntu 16.04 was released less than a week ago, making it more "modern" than Debian 8 by some definitions :)  In any event, Xenial will become the new base distribution once most hosting providers have finished rolling out their images--probably within the next month or so.

Using only the LTS releases (as opposed to switching to something like version 15.10 when it came out last October, for example) ensures that any users who keep a Streisand server around for an extended period of time won't be left behind on APT security updates. Additionally, as far as being "mainstream" is concerned, Ubuntu is officially available on many, many, _many_ more providers than Debian is. That ubiquity is important to me because I want lots of people to be able to use it.

While I respect, love, and use Debian a lot, I'm personally much more concerned about fighting censorship in as many places as possible than I am about, say, whether or not Ubuntu should have signed an unpure trademark agreement with Mozilla to use the Firefox name and logo. (Although I will readily admit that the Iceweasel replacement logo is pretty dope.)

Also, it looks like I forgot to close this issue. You can see that the initial post was someone wanting to run Streisand on Ubuntu 14.04 back when Debian 7 was the base distro, and now the penultimate post will be someone wanting to use Debian 8 instead of Ubuntu 14.04. The symmetry is absolutely beautiful.

You can never make everyone 100% happy, though I am doing my best to try.

**Comment by hydrandt** [comment]
BTW Firefox is back in Debian! :-)

http://news.softpedia.com/news/debian-finally-switches-iceweasel-name-back-to-firefox-500966.shtml
