### ISSUE TITLE
A Little Help with Surge for iOS

### ISSUE THREAD

**Issue by paulg1981** [jlund/streisand#542]
Hello,
I have just installed and setup the streisand stack and I am loving it, thank you!

I noticed that the potato client has a dns leak so I am attempting to use Surge for iOS instead. I am having some trouble configuring it and was hoping someone could help me out?

I have the following in "Edit Configuration" 

Name - Streisand
Log Level - notify [default]
External Controller Access - off [default]
ipv6 support - off [default]

Proxy has one entry with the following:
Name - ShadowSocks
Proxy Type - Socks5
Server - My server ip from streisand
Port - My Port from streisand
Username - blank [default]
Password - long list of characters from streisand

Rules has one rule with the following:
Final - ShadowSocks

Nothing in Local DNS Vaping [default]
Nothing in URL Rewrite [default]

HTTPS Decryption is off [default]

Advanced
Bypass System Related - On [default]
Allow Wifi Access - Off [default]
Skip Proxy - 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local [default]
DNS Override - 8.8.8.8.,8.8.4.4

I have marked the settings I didn't change with [default] for clarity. 

I know I must be missing something simple but this is my first time with shadowsocks. I appreciate any help you can provide.

**Comment by cpu** [comment]
Hi there, we recently updated the shadowsocks-libev server & the configuration that Streisand uses. I'm going to close this issue since it relates to the outdated configuration & server version.

If you recreate your Streisand server with the latest code from master & are still having trouble configuring your client please re-open this issue & we can help triage.

Thanks!
