### ISSUE TITLE
ip/server provider anonymity?

### ISSUE THREAD

**Issue by chadmasso** [jlund/streisand#571]
Couldn't google/aws, etc. just hand over the owner of the server located at the ip address in question? So basically setting up a vpn on one of these providers is just shifting the trust that they won't give away your info? What steps can be taken for complete anonymity short of Tor?

**Comment by Snaver** [comment]
Streisand is an anti-censorship tool ;) Not an all in one privacy/anonymity solution.

Either way I can't imagine much (if any) data/traffic is left stored on the server as it transits through.. So 'handing over' the server won't reveal much. Unless the box is taken control of.

Rotating servers between providers every couple of months wouldn't hurt.

**Comment by jlund** [comment]
Good question! Single-hop VPN connections can help provide a meaningful layer of censorship resistance, security, and enhanced privacy, but they are not designed to be resilient to this type of attack, and that's true no matter where they are located. Streisand sets up a Tor Bridge because of its strong anti-censorship properties, and if you truly require anonymity you need to be using a project like Tor or I2P while also combining them with a lot of other practical considerations (because these projects are not perfect).

For what it's worth, I think it's far less likely that a reputable cloud hosting provider is going to try to sell my VPN-routed browsing history to advertisers than, say, Verizon (who has already tried this).
