### ISSUE TITLE
DNS Issue on PfSense Box

### ISSUE THREAD

**Issue by johnvoncolln** [jlund/streisand#573]
I'd like to pass all my network traffic from my pfsense box (router) through streisand.

I've got my streisand server setup and have created a openvpn client on pfsense, which is connecting.  I can ping out and hit several IP addresses and connect to my Streisand server, but it's not resolving any domains.

How does DNS need to be set up on the client side?  This part is a bit grey...  And if you have any specific information on this pertaining to PfSense router, that would be extra helpful.

**Comment by jlund** [comment]
I haven't ever done this before, unfortunately, but you could try configuring pfSense to use `10.8.0.1` or `10.9.0.1` as the DNS server.

**Comment by johnvoncolln** [comment]
I'm not sure what I did, but it's working now...

**Comment by lilbro1062000** [comment]
https://chubbable.com/setup-pfsense-as-openvpn-client
step 5 and 6 
create a new interface for your new vpn 
and 
create a outbound firewall rule.
still closed but i was having DNS issues as well.

**Comment by softwareuser99** [comment]
Hi, sorry, I know this issue is closed. John (or anybody really), could you possibly guide me on how to configure pfsense to connect to Streisand? I've been using Streisand for a year or so on an OpenWRT Asus R7000 Router and recently swapped this for a Zotac Mini PC and Pfsense. Really happy with pfsense as it allows a lot more customization and sits on a stronger PC; however I can't get OpenVPN to connect to Streisand (normal direct, port 663). I've added the interface, opened the firewall but still not success. 

Logs on the server indicate TLS handshake issues and the client keeps reconnecting, possibly still a firewall issue but I am a bit lost. My main issue is that I am not 100% sure of the OpenVPN client settings I applied, using the Streisand ovpn file. If you could share some insights on how you set up your pfsense openvpn client, that would be really helpful. I am contemplating creating a video tutorial on youtube once I get it running myself, to help others who are also struggling....

Thanks a lot!
