### ISSUE TITLE
Erroring out on gce-network : Create Network due to pycrypto?

### ISSUE THREAD

**Issue by sawtoothwave** [jlund/streisand#584]
Hey there- apologies if this is a super n00by question but in I'm way over my head technically here and just attempting to follow the step-by-step instructions, and don't have the technical chops to troubleshoot if an error pops up. Everything looks like it's going ok until the above task, at which point the setup fails and slings me the error message in the attached screenshot.

Any ideas what's missing? I think I successfully installed all the packages leading up to this step. I'm running OSX Yosemite 10.10.5 on a MacBook Pro Retina 13-inch late 2013 if that helps.
<img width="651" alt="screen shot 2017-04-08 at 12 47 17 pm" src="https://cloud.githubusercontent.com/assets/7399341/24830727/8910a3be-1c59-11e7-94d7-3f4405af0766.png">

Thanks very much for any clarity you could provide and thanks also for putting together this whole thing in the first place.

**Comment by cpu** [comment]
Hi @sawtoothwave,

The error text indicates that it might be a problem with `PyCrypto` on your system. As a first step can you provide the output from running:
`pip show pycrypto`

**Comment by sawtoothwave** [comment]
Wow, thanks for the quick response! No response at all, it just processed for a moment and then gave me the command prompt back.

**Comment by cpu** [comment]
@sawtoothwave It sounds like you have a problem with your `pip` installation. You might find that you can get better support through one of the Pip or Python support channels.

I'm going to close this issue since I don't believe it will be possible to fix from Streisand's codebase. If you are able to get your `pip` issues cleared up and are still unable to provision a GCE instance please feel free to reopen and we can go from there!

**Comment by sawtoothwave** [comment]
Okay, gotcha. Thanks for looking into it. Would you suggest that I try using a different provider than Google, or is it going to run into the same problem?

**Comment by cpu** [comment]
@sawtoothwave It's hard to say for sure! This particular error was related to the Google provisioning, so switching providers may help. That said, if other requirements were skipped somehow due to a pip related breakage you might just hit a different error. Maybe worth a shot?

**Comment by sawtoothwave** [comment]
Seems worth it! I'll update this ticket (even though it's closed) if another provider works; maybe that'll help other people with PyCrypto problems...

**Comment by sawtoothwave** [comment]
:-/ didn't seem to work. I tried Linode and got a new error - looks like pycurl this time rather than pycrypto

<img width="646" alt="screen shot 2017-04-08 at 2 11 14 pm" src="https://cloud.githubusercontent.com/assets/7399341/24831289/4f04fc5e-1c65-11e7-9768-682902053d67.png">

Anyway, hopefully this helps further development of the process. I'll keep an eye on updates; maybe this shines a light on a place where other packages need to be installed or verified before streisand can execute all the way through. Thank you!

**Comment by sawtoothwave** [comment]
Got it working on Linode! It seems perhaps pycurl wasn't installed correctly the first time around. Maybe that caused the PyCrypto problem too.

**Comment by markwyner** [comment]
I have this same issue, and can't seem to get past it. I tried installing ansible 2.2.2.0, as suggested in issue #629 to no avail. When I check my version of ansible I get the following returned:

```
ansible 2.3.1.0
  config file = /Users/markwyner/Documents/VPN/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul  7 2017, 17:40:26) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
I'm running Homebrew 1.2.4 and Python 2.7.10, my Google Cloud instance is brand new, and I just cloned the Streisand repo, so that's current. Perhaps is there an issue with ansible seeking that python version 2.7.13?

I'd love any help anyone might have. Thanks in advance.
