### ISSUE TITLE
Modify settings

### ISSUE THREAD

**Issue by spartanhooah** [jlund/streisand#591]
Is it possible to modify any of the settings of the services that streisand sets up? In particular, I suspect that the 256-bit encryption may be bogging down my older router, so it'd be nice to be able to try turning that down to 192-bit to see if I get better bandwidth.

**Comment by cpu** [comment]
@spartanhooah I could point you in the right direction if you mentioned which services & options you were wanting to tweak.

**Comment by cpu** [comment]
@spartanhooah You can find the settings for [OpenVPN's key sizes, ciphers and digest algorithm](https://github.com/jlund/streisand/blob/master/playbooks/roles/openvpn/defaults/main.yml#L17:L20) in the OpenVPN role's [defaults file](https://github.com/jlund/streisand/blob/master/playbooks/roles/openvpn/defaults/main.yml).

One thing to check! Are you sure you're not prematurely optimizing? I would encourage you to try the settings Streisand ships by default until you are certain they are causing you performance issues. Can your router support Wireguard?

**Comment by spartanhooah** [comment]
I'm certain that my bandwidth is decreased when connected to streisand. Normally I get ~73 Mbps download, but when the OpenVPN client on my router is enabled, I see 3 Mbps at most. It doesn't look like dd-wrt supports Wireguard.

**Comment by nickolasclarke** [comment]
@spartanhooah its quite normal to see massive drops in performance over VPN, depending on where you are based, the protocol you are using, where your server is based, etc. If you can provide more info about specifics of how your testing, where you are based, etc etc we may be able to help. You dont need re-run streisand to make any changes, however. 

Streisand, at its core, is just a bunch of scripts to get things up and running. It simply orchestrates the installation and configuration of all the various services, and then it is done. You can learn about and modify all the various services however you'd like post installation. Some of them are reliant on each other though to varying degrees. Streisand is arguably also designed to be "one size fits all". You should use the instance until it is blocked or otherwise no longer usable, and instead of nursing it back to health, you just start a new instance and carry on (see pets vs cattle infrastructure).

 As such, additional support on customizing particular parts of different services (like adding more users to openvpn, or installing additional services on the same server, changing network settings, etc) is probably outside the scope of the streisand project. That said, we're a friendly bunch, and will help as we can. But you may have better luck going asking groups specific to the service you want to customize for help on making changes.

**Comment by spartanhooah** [comment]
Alright, good to know about what role streisand actually plays. I'm in San Antonio and set up the VPN on a DigitalOcean droplet in their San Francisco data center. I'm testing via testmy.net's combined test on my desktop, which has a wired Ethernet connection to my WNDR3700v3 router running dd-wrt.

**Comment by spartanhooah** [comment]
Should I be able to SSH into the server that streisand set up? I guess that would be the first step to configuring anything in-place.

**Comment by nickolasclarke** [comment]
@spartanhooah, yes, it uses the ssh key pair that you designate when doing running through the setup. as long as you have access to that, you should be able to connect via SSH.

**Comment by zx2c4** [comment]
> It doesn't look like dd-wrt supports Wireguard.
OpenWRT/LEDE does.

**Comment by cpu** [comment]
I don't think there's any remaining action for Streisand to take from this issue so I'm going to close it. Thanks!
