### ISSUE TITLE
Suggestion: Configurability while installing

### ISSUE THREAD

**Issue by TychoSchenkeveld** [jlund/streisand#614]
Would it be possible to have it configurable which protocols are being installed?

For example, I don't need shadowsocks or openvpn, and I definitely don't want tor. 

At the moment I've been uninstalling stuff afterwards but I'm always a bit wary of how this affects the rest. A fully supported configurable installer would be great.

**Comment by cpu** [comment]
Hi @TychoSchenkeveld,

Agreed, being able to choose which services are installed would be great. There are several tickets open requesting this feature (https://github.com/jlund/streisand/issues/23 is probably the oldest). I'm going to close this issue since it's a duplicate.

Enabling a pick & choose service deployment is high on my priorities to address and I suspect you'll see some progress from myself or another implementer in the near future.

Thanks!

**Comment by TychoSchenkeveld** [comment]
Oops, sorry for raising the duplicate. I had a quick look but there were so many tickets that I didn't notice it. Sorry!

Thanks very much for your work on this!

**Comment by cpu** [comment]
No problem! Hoping to have the number of open issues reduced shortly to make it easier to find things.
