### ISSUE TITLE
Firewall Rules 

### ISSUE THREAD

**Issue by atulsian89** [jlund/streisand#653]
I want to install shadowsocks R on a server which is running on Streisand. I'll using random port for SSR. Im not sure which commands to use to make SSR work and allow traffic pass through that port. 

Any help would be greatly  appreciated.

**Comment by cpu** [comment]
Hi @atulsian89,

I recommend using `ufw` to add a new rule for the port you're interested in. I believe you will want to add a rule for **both** TCP and UDP as well for Shadowsocks. [`man ufw`](http://manpages.ubuntu.com/manpages/yakkety/en/man8/ufw-framework.8.html) on your server is a good place to start.  The [Ubuntu community documentation for UFW](https://help.ubuntu.com/community/UFW) is another good resource. Hope these help! 

I'm going to close this issue since the firewall management you will have to do is generic to Ubuntu servers and not Streisand specific, and may be better suited for a general Ubuntu / system administration forum (like [server fault](https://serverfault.com/) than the Streisand repo.
