### ISSUE TITLE
Failure on [ssh : Add the SSH forwarding user and generate a key]

### ISSUE THREAD

**Issue by GabeIsman** [jlund/streisand#671]
I'm getting the following error while trying to run the setup script. Run on both AWS and DigitalOcean, same error in both places.

Any help super appreciated!

```
TASK [ssh : Add the SSH forwarding user and generate a key] ********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'int' is not iterable
fatal: [162.243.31.140]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mGQX6b/ansible_module_user.py\", line 2168, in <module>\n    main()\n  File \"/tmp/ansible_mGQX6b/ansible_module_user.py\", line 2150, in main\n    (rc, out, err) = user.ssh_key_gen()\n  File \"/tmp/ansible_mGQX6b/ansible_module_user.py\", line 619, in ssh_key_gen\n    (rc, out, err) = self.execute_command(cmd)\n  File \"/tmp/ansible_mGQX6b/ansible_module_user.py\", line 303, in execute_command\n    return self.module.run_command(cmd, use_unsafe_shell=use_unsafe_shell, data=data)\n  File \"/tmp/ansible_mGQX6b/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2120, in run_command\n  File \"/usr/lib/python2.7/posixpath.py\", line 287, in expandvars\n    if '$' not in path:\nTypeError: argument of type 'int' is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by cpu** [comment]
@GabeIsman Can you provide more information about your system?

##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*

**Comment by cpu** [comment]
I'm going to close this issue since there hasn't been a reply with the required information. We can reopen if it becomes actionable. Thanks!

**Comment by GabeIsman** [comment]
Hey @cpu,

Sorry for the slow response.

Client OS: OS X 10.12.5
ansible 2.3.0

**Comment by cpu** [comment]
@GabeIsman No problem, thanks for sharing your Ansible version.

I have to admit I'm pretty baffled. That error appears to be a stacktrace from the [Ansible user module](http://docs.ansible.com/ansible/user_module.html). I eyed the Streisand task that's using it and can't spot an obvious reason this would fail. I wasn't able to find an open Ansible bug for this but I may have missed one (this particular non-iterable type error is very common in all Python projects and muddies the search considerably).

Since 2.3.0 is a little bit out of date I think the next best step is to upgrade your Ansible and see if the error is resolved. Do you want to give that a shot and report back with the version you tried & whether the error persists?

Thanks!

**Comment by GabeIsman** [comment]
@cpu Just wanted to follow up and say that this problem is resolved with the latest Ansible, and latest streisand. Thanks for your help! Got a server up and running!

**Comment by cpu** [comment]
@GabeIsman Excellent! Thanks for reporting back, I'm really glad to hear that the update worked and you're on your way! :tada:
