### ISSUE TITLE
No Generated-Docs Folder

### ISSUE THREAD

**Issue by randy2134** [jlund/streisand#729]
Hello all,

i recently spun up a new streisand server, as my new laptop for whatever reason was not able to connect to wireguard on my old one. 

Issue: When completing the server, I cannot find the generated Doc's folder. 
complications - I couldn't get the server to spin up properly under the instructions, I kept getting an error saying Dopy 3.5 was not installed, although it was. I corrected this by spinning up my Streisand droplet using a python virtual environment, which worked fine. I dont know if the virtual environment prevented my Generated Doc's file from being created. I've tried it several times now with no luck. 

### Expected behavior:
Generad Docs folder in my streisand folder

### Actual Behavior:

nothing

### Steps to Reproduce:
1.

**Comment by cpu** [comment]
@randy2134 Sorry to hear you're having trouble. 

>  as my new laptop for whatever reason was not able to connect to wireguard on my old one.

Your laptop was probably running the latest client code from the PPA while the server was running an older version (or vice versa). There was a breaking change upstream a short while ago.

>  I dont know if the virtual environment prevented my Generated Doc's file from being created. I've tried it several times now with no luck.

Right now I don't think there isn't enough information to help you. In particular it would be helpful to see the log output from Ansible (shared as a link to a Gist since it will likely be quite long).

>  I kept getting an error saying Dopy 3.5 was not installed, although it was. 

It looks like Manjaro is Arch based, which ships Python3 by default. I believe the playbooks will be running under Python2 if you use the `streisand` wrapper. Have you tried using `pip2` to install `dopy` instead of `pip`?

**Comment by randy2134** [comment]
cpu - thanks for taking the time with my question. I'm not sure what the error was, but I managed a pretty solid workaround that I read from someone else here in the forums. Server is up and working great.Id recommend the following for anyone who has ANY installation issue - I'll post all the commands in case anyone just wants to copy this and do a quick cut and paste:

create a fresh $5 droplet on digitalocean, ubuntu 16.04.2 - your going to spend about $.02 for this

ssh into your new droplet
sudo apt update && sudo apt dist-upgrade -y && sudo apt autoremove -y

copy your id_rsa and id_rsa.pub file  to ~/etc/ssh  (your going to destroy this droplet in a few minutes anyway) - I used filezilla

cd /etc/ssh
chmod 0600 id_rsa
cd
sudo apt-get install git
sudo apt-get install python-paramiko python-pip python-pycurl python-dev build-essential
sudo pip install ansible markupsafe             

(note - from here on UBUNTU starts screaming at you to upgrade python - don't do it)
sudo pip install dopy==0.3.5
git clone https://github.com/jlund/streisand.git && cd streisand
./streisand

again thanks for your help

**Comment by cpu** [comment]
@randy2134 I'm glad that you were able to find a different solution to your problem. As a quick note, it's much better from the maintainer perspective if we can diagnose & fix your initial problem instead of closing it without enough information because an alternative approach worked.

The instructions you're sharing are for provisioning Streisand on the *same machine* you're running it on, e.g. what we sometimes call "local provisioning mode". I have a PR out to make this a supported feature: https://github.com/jlund/streisand/pull/724 I **do not** recommend that anyone follow your instructions for this since it's an unsupported workaround and it isn't clear how its related to your initial issue.

Enjoy your Streisand server! Thanks!
