### ISSUE TITLE
upgrade and dist-upgrade Asks to Overwrite 50unattended-upgrades, then breaks

### ISSUE THREAD

**Issue by marcusguttenplan** [jlund/streisand#759]
### Expected behavior:
Trying to upgrade the kernel on my streisand instance (GCE, ubuntu 16.04.2) with `apt-get upgrade` and `apt-get dist-upgrade`. Should work without issue.

### Actual Behavior:
`apt-get upgrade` asks about installing a new version of file `50unattended-upgrades`, which will overwrite local changes. Erring on caution, told it no. After telling it no, `apt-get upgrade` and `apt-get dist-upgrade` throw error `N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension`. Checked possible related issues https://github.com/jlund/streisand/issues/115 and https://github.com/jlund/streisand/issues/561, but neither seem relevant. Same issue here https://askubuntu.com/questions/829370/n-ignoring-file-50unattended-upgrades-ucf-dist-in-directory-etc-apt-apt-con

### Steps to Reproduce:
1.  `apt-get upgrade`
2. Wait for prompt `new version of file 50unattended upgrades is available`
3. Select "no"
4. Try to run `apt-get upgrade` and `apt-get dist-upgrade` again

##### *Version of Ansible, using `ansible --version` :* 2.3.0.0

I hate opening an issue, I'm sorry! Just want to see if this is a known problem, or fixable on my end. Just don't want to break streisand in case the unattended-upgrades file has been customized.

**Comment by cpu** [comment]
Hi @marcusguttenplan - at this point I can't say that we officially support updating in-place except for security updates. That said it seems like you've done the right thing here: prevented the upgrade from replacing the Streisand `50unattended-upgrades` file that, as you suspected, is customized.

The warning "N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension" can be ignored. You can fix it by removing `/etc/apt/apt.conf.d/50unattended-upgrades.ucf-dist`. This is the copy of the file that the upgrade *wanted* to replace the Streisand file with but didn't. Instead it put it in the directory with a `ucf-dist` extension, which apt now says it will ignore since it has an unexpected extension in a directoy meant to contain only files without extensions.

Hope that makes sense! I'm going to close this issue since for now there isn't anything to change on the Streisand side.

**Comment by marcusguttenplan** [comment]
That's great help, thanks for taking the time @cpu! Do you have any idea what modifications streisand makes to the unattended upgrades file? I will have to diff them and see if I can manually update in-place.

**Comment by cpu** [comment]
Hi @marcusguttenplan,

The `50unattended-upgrades` file that Streisand creates [is here, in `playbooks/roles/common/files/50unattended-upgrades`](https://github.com/jlund/streisand/blob/0265d154a86c0945f30d450b09e4f23f9df50556/playbooks/roles/common/files/50unattended-upgrades). You should be able to diff that with the distro config. 

Hope that helps!
