### ISSUE TITLE
Streisand Mirror issue

### ISSUE THREAD

**Issue by AaronForce1** [jlund/streisand#766]
### Expected behavior:
Mirror tunnelblick
### Actual Behavior:
Streisand 404
### Additional Details:

TASK [streisand-mirror : Mirror Tunnelblick for OS X] **************************
fatal: [54.241.146.224]: FAILED! => {"changed": false, "dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://tunnelblick.net/release/Tunnelblick_3.7.1a_build_4812.dmg"}

**Comment by cpu** [comment]
@AaronForce1 Your Streisand repo is out of date. [Master currently mirrors 3.7.1b](https://github.com/jlund/streisand/blob/8b6d2b1721f3cf7668e822f53239442422d1a3af/playbooks/roles/streisand-mirror/vars/openvpn.yml#L34) whereas you are trying to mirror 3.7.1a. This was fixed with https://github.com/jlund/streisand/commit/4072d9354a24a453f06e12e888ac296cd3930174 and you should be able to `git fetch origin && git pull` from your Streisand directory to get the latest code.
