### ISSUE TITLE
`generated-docs` folder is not created after non-fatal errors

### ISSUE THREAD

**Issue by skaurus** [jlund/streisand#772]
I tried to install `streisand` on Scaleway and it failed during WireGuard task - because they use custom kernel and there are no headers.

Docs weren't generated at all, but actually the rest of `streisand` services should be usable.
I think allowing install procedure to partially success would increase `streisand` compatibility quite noticeably.

**Comment by cpu** [comment]
Hi @skaurus, thanks for opening an issue.

> I tried to install streisand on Scaleway and it failed during WireGuard task - because they use custom kernel and there are no headers.

Yes, presently we do not support Scaleway.

> Docs weren't generated at all, but actually the rest of streisand services should be usable. I think allowing install procedure to partially success would increase streisand compatibility quite noticeably.

I agree with the idea of being able to support a "partial" Streisand install, but I disagree that allowing the install procedure to partially succeed is the best way to support that goal.

My concern with making partial success generate docs as if the install succeeded is that it's likely to cause lots of confusion & a large support burden on our end if folks encounter errors during the install, think it succeeded because of the doc generation, and then have to ask for help because certain services are in half-installed/broken states.

If the Wireguard role were optional (see https://github.com/jlund/streisand/issues/746) then it would be easy to resolve the failures by disabling the Wireguard role for your Scaleway install. In that case there would be no errors and the install would complete successfully and you could use the other services.

Do you think having the modularity support from #746 completed would be sufficient for your needs?

**Comment by skaurus** [comment]
Hi @cpu,

Thank you for detailed response! Yes, modularity would solve this.

**Comment by cpu** [comment]
@skaurus Great - glad to hear it! I expect to open a PR against master to make Shadowsocks and Wireguard optional in the next few weeks once I have time to resolve some conflicts, stay tuned!
