### ISSUE TITLE
`id_rsa.pub` is required but not documented

### ISSUE THREAD

**Issue by openspacex** [jlund/streisand#844]
Hi. Thanks for the amazing work.

[Expected Behaviour]

I think option 8 should absolutely ask these questions:

1] Server SSH Port [might not be 22 if server was previously set up and hardened]
2] Server SSH User [instead of requiring the ANSIBLE_SSH_USER variable to be previously known and provided]
3] SSH key file location [not just use ~/.ssh/id_rsa + see issue below] OR password

Issue: Additionally, **the docs don't say** that an ~/.ssh/id_rsa**.pub** file is also required, something that is completely not necessarily there if the key wasn't generated on that client AND not renamed [something I always do, and therefore only copy <named-key> to "id_rsa" for streisand to work, something that shouldn't even be required, I think].

[Actual Behaviour]

1] Streisand assumes SSH port 22
2] Streisand requires user's knowledge of ANSIBLE_SSH_USER var in case of custom SSH user
3] Streisand requires id_rsa [**AND id_rsa.pub although not specified anywhere in the docs** as far as I can tell]

[Steps to Reproduce]

Use option 8

[Ansible Version]

ansible 2.3.1.0

Thank you

**Comment by cpu** [comment]
Hi @openspacex,

Thanks for the feedback! I appreciate it.

The existing server provisioning feature is marked as "advanced" in-part because I believe it should only be used by proficient administrators. I'm of course open to making it better/easier but its a lower priority than other work that needs to be done. When I added this support I did it largely because folks were trying it on their own and running into trouble that was easy to add guardrails for.

> 1] Server SSH Port [might not be 22 if server was previously set up and hardened]

This has been requested before: https://github.com/jlund/streisand/issues/742 Streisand doesn't provision SSHD on anything but 22 and so this is a nice-to-have for advanced users. I'm open to reviewing a PR that better documents the `ansible_ssh_port` feature of Ansible inventories.

> 2] Server SSH User [instead of requiring the ANSIBLE_SSH_USER variable to be previously known and provided]

Open to reviewing a PR that would improve on this!

> 3] SSH key file location [not just use ~/.ssh/id_rsa + see issue below] OR password

We've taken a stance against password authentication in the past and likely wouldn't compromise on that. Being able to specify a SSH keypair is [on my radar](https://github.com/jlund/streisand/issues/300). I expect we will get to it sooner or later (PRs welcome!).

> Issue: Additionally, the docs don't say that an ~/.ssh/id_rsa**.pub** file is also required, something that is completely not necessarily there if the key wasn't generated on that client AND not renamed [something I always do, and therefore only copy to "id_rsa" for streisand to work, something that shouldn't even be required, I think].

I don't think its strange to assume that the RSA private key will have a public key with it, it's a SSH key**pair** by definition and that's standard `ssh-keygen` behaviour (which is what the instructions currently document you use to create `id_rsa`). Since the steps in the documentation will create this file automatically I don't think its worth documenting it explicitly.

It sounds like you're describing a more complicated scenario where keys are generated elsewhere and that's not a Streisand use-case. If you want to do that I think it's fair to say you're an advanced user and should be able to make it work on your own. Adding documentation for this will likely confuse the use-cases we're trying to support.

**Comment by nikksno** [comment]
Hi @cpu 
Thanks for the feedback
I'll try to get something working for points 1 and 2.
I agree with password auth, I would never allow it myself, so if you agree, great.
I really think that being able to specify an ssh key would be great.
For the time being, I'm just saying that [this](https://github.com/jlund/streisand#running-streisand-on-other-providers-advanced) part of the docs should simply say, instead of:

```The server must be accessible using the $HOME/id_rsa SSH Key```

this:

```Both the private and public keys of the server's ssh keypair must be placed in the $HOME directory with default ssh-keygen names, as such: $HOME/id_rsa and $HOME/id_rsa.pub.```

This is because anyone who uses ssh-keys on multiple machines or syncs them [i.e. with Termius] is very used to only copy the private key locally when needing to interact over ssh with such server from a local terminal. It is never required to also copy the public part back to the machine.

It is instead required here, and the docs only explicitly mention the private part. I simply think it makes sense to mention the public key as well.

Thanks!

**Comment by openspacex** [comment]
Hi @cpu 
Thanks for the feedback
I'll try to get something working for points 1 and 2.
I agree with password auth, I would never allow it myself, so if you agree, great.
I really think that being able to specify an ssh key. would be great.
FOr the time being, I'm just. saying that [this](https://github.com/jlund/streisand#running-streisand-on-other-providers-advanced) part of the docs should. simply say, instead of:

```The server must be accessible using the $HOME/id_rsa SSH Key```

this:

```Both the private and public keys of the. server's ssh keypair must be placed in the $HOME directory with default ssh-keygen names, as such: $HOME/id_rsa and $HOME/id_rsa.pub.```

This is because anyone who uses ssh-keys on multiple machines or syncs them [i.e. with Termius]. is very used. to only copy the private key locally when needing to interact over ssh with such. server from a local terminal. It is never required to also copy the public part back to the machine.

It is instead required here, and the docs only explicitly mention the private part. I simply think it makes sense to mention the public key as well.

Thanks!

**Comment by cpu** [comment]
> This is because anyone who uses ssh-keys on multiple machines or syncs them [i.e. with Termius] is very used to only copy the private key locally when needing to interact over ssh with such server from a local terminal. It is never required to also copy the public part back to the machine. It is instead required here, and the docs only explicitly mention the private part. I simply think it makes sense to mention the public key as well.

I'm still adverse to adding more information to the documentation that won't apply to the vast majority of our users.

What about this for an alternative: from a cryptographic perspective the SSH private key has all of the information required to reconstitute the public key. The `ssh-keygen` tool has support for that. I'd rather see an update to the Ansible playbooks proposed that would detect if the public key file is missing and use `ssh-keygen`'s `-y` option to automatically create the public key file as required without needing manual intervention. From `man ssh-keygen`:

```     
-y      This option will read a private OpenSSH format file and print an OpenSSH public
             key to stdout.
```

Would that suffice?

**Comment by nopdotcom** [comment]
My primary SSH key is on a Yubikey, and the private part isn't going anywhere. I will never have a normal id_rsa again if I can help it. 

I agree it is poor hygiene to let your a daily SSH id_rsa get outside your control. For attackers who possess id_rsa, all they need is a passphrase sniffed once to fully steal/clone the credential. Didn't people use sourceforge logins to do this attack at some point, when people would retype their passwords to ssh out of the sf shell nodes?

I think there are actually two sets of keys here: your regular keys, and the Ansible deployment keys. If we need a keypair for deployment, I think we need to generate one. Somebody needs to generate one (because some cloud services need a fresh one, right?) We would create our own id_deploy_streisand and id_deploy_streisand.pub. 

I think those new Ansible SSH keypairs need to go somewhere in ~/streisand/, notionally similar to generated-docs. Deployers may need the private part later.

It might be cute to add `ssh-add -L | head -1` to the authorized_keys on the streisand node. Maybe way too cute.

**Comment by cpu** [comment]
@nopdotcom This sounds unrelated to the actionable part of this ticket: describing that there needs to be a public key file corresponding to the expected `id_rsa` private key. 

I agree that there are other improvements - can you add those thoughts to https://github.com/jlund/streisand/issues/300 instead of here?

**Comment by nopdotcom** [comment]
Got it. I will avoid reading and posting to active GH discussions from mail again, too. :‐)

**Comment by openspacex** [comment]
@cpu ok that sounds reasonable, I'll add it to the list of stuff to try out and see. I'll work on all three points and get back to you. Thanks!

**Comment by cpu** [comment]
@openspacex Any luck? Should I close this issue?

**Comment by cpu** [comment]
I'm going to close this issue since I don't believe there are any immediate actions to be taken. I would review a PR to auto-generate the public component of the SSH private key if required. Please feel free to reopen if there is more discussion to be had. Thanks!
