### ISSUE TITLE
TASK [tor-bridge : Downloading Tor Browser Bundle files and signatures for locale (fr)] failed

### ISSUE THREAD

**Issue by dfroberg** [jlund/streisand#865]
### Expected behavior:
Installation without errors
### Actual Behavior:
```
TASK [tor-bridge : Downloading Tor Browser Bundle files and signatures for locale (fr)] *************************************************************************************************************************************
failed: [67.207.94.17] (item=https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe"}
failed: [67.207.94.17] (item=https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc"}
failed: [67.207.94.17] (item=https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg"}
failed: [67.207.94.17] (item=https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc"}
changed: [67.207.94.17] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux32-7.0.3_fr.tar.xz)
changed: [67.207.94.17] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux32-7.0.3_fr.tar.xz.asc)
changed: [67.207.94.17] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux64-7.0.3_fr.tar.xz)
changed: [67.207.94.17] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux64-7.0.3_fr.tar.xz.asc)

TASK [tor-bridge : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ************
Pausing for 20 seconds
```
### Steps to Reproduce:
1. follow instructions to install on an DO droplet from a linux workstation

**Comment by kylevedder** [comment]
+1 on the bug.

**Comment by cpu** [comment]
This has been reproduced and it appears that `7.0.3` was a Linux only release. Streisand's mirroring expects that the latest version is equal across all platforms and is failing to download `7.0.3` for Windows and OSX.

On the upside, this should be a non-fatal error that allows provisioning to proceed. I'm not clear yet what the best fix is. We might need to switch to hardcoding the version ala some of the other mirrored clients & bumping manually with fresh commits.

**Comment by nathanpruitt** [comment]
I received this error today as well. New install on DO. Followed steps as instructed.

Provisioned from MacBook Pro SierraOS

Direct copy error output:

TASK [tor-bridge : Downloading Tor Browser Bundle files and signatures for locale (fr)] ***
failed: [IP-REDACTED] (item=https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe"}
failed: [IP-REDACTED] (item=https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/torbrowser-install-7.0.3_fr.exe.asc"}
failed: [IP-REDACTED] (item=https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg"}
failed: [IP-REDACTED] (item=https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.3/TorBrowser-7.0.3-osx64_fr.dmg.asc"}
changed: [IP-REDACTED] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux32-7.0.3_fr.tar.xz)
changed: [IP-REDACTED] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux32-7.0.3_fr.tar.xz.asc)
changed: [IP-REDACTED] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux64-7.0.3_fr.tar.xz)
changed: [IP-REDACTED] => (item=https://dist.torproject.org/torbrowser/7.0.3/tor-browser-linux64-7.0.3_fr.tar.xz.asc)

TASK [tor-bridge : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)

**Comment by alimakki** [comment]
Tor updated the TBB to 7.0.4 and all platforms appear to be in sync, effectively resolving this issue.
