### ISSUE TITLE
Shadowsocks did not work out-of-the-box for Google Cloud

### ISSUE THREAD

**Issue by littlebtc** [jlund/streisand#882]
I had created a Streisand instance with all default settings on `asia-east-1` (Taiwan) in Google Cloud, and I can get OpenConnect working but not the shadowsocks.

All requests seems to be timed out. (Client is Shadowsocksx-NG on macOS)
I had try to change `shadowsocks.conf` to listen `0.0.0.0`, but it still doesn't work.

-------------
Sorry for rushing creating issue, I will investigate more on this.

**Comment by cpu** [comment]
@littlebtc One suggestion is to edit `/etc/default/shadowsocks-libev` on the Streisand server to add `-v` to the `DAEMON_ARGS`. After that `systemctl restart shadowsocks-libev` and try to connect your client & browse websites. Afterwards you should be able to see more verbose output from shadowsocks in `journalctl -e` which may help diagnose the problem.

**Comment by littlebtc** [comment]
![2017-08-10 8 57 53](https://user-images.githubusercontent.com/82419/29149982-22d9d1a8-7daa-11e7-8eb8-d058a7c9ad4f.png)
I ran with -v but it seems not so many info?

**Comment by cpu** [comment]
@littlebtc Let's try seeing what's there without all of the extra chatter. Can you:

1. On the server: `systemctl restart shadowsocks-libev` to get a clean start
2. On the client: Connect to the server with your shadowsocks client & browse to a few sites
3. On the server: `journalctl --since today -u shadowsocks-libev --no-pager` & share the results as a [new Github gist](http://gist.github.com/) that you can link to from here.

Thanks!

**Comment by littlebtc** [comment]
It seems to be my fault. Closed as it works on my iPad :(
