### ISSUE TITLE
Unable to download torbrowser-install-7.0.4_fr.exe.asc

### ISSUE THREAD

**Issue by Untuned** [jlund/streisand#888]
### Expected behavior:
Downloads the key.
### Actual Behavior:
Fails.
### Steps to Reproduce:
1. Run the streisand installer.

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
`failed: [X.X.X.X] (item=https://dist.torproject.org/torbrowser/7.0.4/torbrowser-install-7.0.4_fr.exe.asc) => {"failed": true, "item": "https://dist.torproject.org/torbrowser/7.0.4/torbrowser-install-7.0.4_fr.exe.asc", "msg": "Failed to connect to dist.torproject.org at port 443: [Errno 104] Connection reset by peer"}`

**Comment by cpu** [comment]
Hi @Untuned,

> Operating System of client: Windows 10 Pro

To clarify, you're running the `./streisand` script from this Windows host? Perhaps with the Linux subsystem? I'm surprised that works! 

>  [Errno 104] Connection reset by peer

This has the smell of transient network issues between your Digital Ocean instance and the Tor mirror. Have you retried since seeing this failure? Does the problem persist?

Thanks!

**Comment by cpu** [comment]
I'm going to close this issue since I suspect it was transient and there hasn't been a reply. Please feel free to reopen this issue if you're still experiencing the problem.
