### ISSUE TITLE
Error Installing on a Linode Instance.

### ISSUE THREAD

**Issue by ianbarton** [jlund/streisand#925]
I have tried installing on a Linode instance, both from my Arch Linux laptop and from another Linode 16.04 Ubuntu server. In both cases I get the following error:

TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] ******************************************************************
fatal: [212.71.249.52]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.010915", "end": "2017-09-05 08:21:24.623229", "failed": true, "rc": 1, "start": "2017-09-05 08:21:24.612314", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}

**Comment by cpu** [comment]
@ianbarton This looks like the error you would see if you installed on an **existing** Linode server. E.g. not one created by the `./streisand` script and giving it your API key. This isn't a supported installation mode because we [do some monkey patching](https://github.com/jlund/streisand/blob/3ce4b8abd15c9fb12d0cc1a9c8dc1d5365e38c3f/monkey/usercustomize.py#L1:L11) to specifically set the kernel of the Linode instance to be one that works with Streisand. The default Linode 16.04 kernel is not compatible with Streisand.

I would recommend letting the Streisand script create the target Linode instance for you. If for some reason that won't work I believe you can change the kernel for an existing server manually by editing the profile of the server and then on the "Edit Configuration Profile" screen under "Boot Settings" changing the value from "Latest 64bit" to "GRUB 2" and saving. You should also reboot the instance before installing on it after making this change.

Good luck!

**Comment by ianbarton** [comment]
Thanks, setting the Boot Setting to GRUB worked for installing on localhost. However, I have a separate issue when trying to let the script create a new Linode. I'll open another issue for that.
