### ISSUE TITLE
non-standard ssh port

### ISSUE THREAD

**Issue by SandMouse** [jlund/streisand#96]
I'm installing Streisand on a VM behind a firewall. We NAT our SSH traffic from a non-standard port to the default port 22 on the VM. But for the outside world the port is e.g. 32002. What changes need to be made so that my machine can contact the Streisand VM on port 32002 to run the setup scripts? Can I add a line to streisand.yml? What should this be? I've tried a couple but when running the playbook it returns: ERROR: Invalid ini entry: 10022 - need more than 1 value to unpack

**Comment by cpu** [comment]
The initial question has been answered so I'm going to close this issue. I don't think this is sufficiently common to be included in the docs at present. Thanks!

**Comment by Scorpion2185** [comment]
@jlund (or anyone) I modified the `inventory` file (in the `inventories` folder).
I ran `ansible-playbook playbooks/streisand.yml` (in the `streisand` folder) but:
```
[...] /streisand# ansible-playbook playbooks/streisand.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 40, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named 'ansible'
```
I need to use a custom ssh port for `Existing server`. 
@cpu  

> The initial question has been answered so I'm going to close this issue. I don't think this is sufficiently common to be included in the docs at present. Thanks!

This is one more case.
Can someone explain me?

**Comment by cpu** [comment]
> I ran ansible-playbook playbooks/streisand.yml (in the streisand folder)

@Scorpion2185 You should use the `./streisand` wrapper script instead of directly invoking Ansible.

> ImportError: No module named 'ansible'

This is an error unrelated to the custom SSH port - Double check you followed the README setup instructions for installing Ansible in a virtualenv.

> This is one more case.

I recommend you open a new issue on the [Streisand discussions repo](https://github.com/streisandeffect/discussions) if you still need help after troubleshooting your Ansible installation and using the wrapper script. The problems you're having aren't related to the original question in this thread so I'm going to lock it to prevent further splintering. Thanks for understanding!
